@startuml
hide empty description

state Root {
    state End
    End --> [*]

    state PowerOff
    PowerOff --> Running : RestorePower

    [*] --> Running
    state Running {
        [*] --> Washing
        state Washing
        Washing --> Rinsing : Rinse

        state Rinsing
        Rinsing --> Drying : Dry

        state Drying
        Drying --> [*]

        Running --> End : Stop
        Running --> PowerOff : CutPower
    }

}


@enduml
