@startuml
hide empty description

state Root {
    [*] --> Off
    state Off
    Off --> Maintenance : TogglePower [Maintenance is On] / log transition Off to Maintenance
    Off --> On : TogglePower [Maintenance Off] / OfftoOn

    state Maintenance
    Maintenance --> Off : TogglePower / MaintainedtoOff

    state On {
        [*] --> DAB
        state DAB
        DAB --> FM : ToggleMode / DABtoFM

        state FM {
            [*] --> Play
            state Play
            Play --> AutoTune : StationLost / PlaytoAutoTune

            state AutoTune
            AutoTune --> Play : StationFound / AutoTunetoPlay

            FM --> DAB : ToggleMode / FMtoDAB
        }

        On --> Off : TogglePower / OntoOff
    }

}


@enduml
