---
title: "Business Models"
date: 2019-05-01
weight: 50
draft: false
---
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:revnumber: v0.1
:revdate: 2020-05-31
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0
:icons: font
:source-highlighter: pygments
:pygments-style: manni

== Codes

The abstraction of a reference table or reference codes.
A code table is an extensible set of values.
You can add values when needed and extend the model with temporal activation if desired.
For example currencies are typical code values with a temporal duration; well-known retired currencies are the European Currency Unit _ECU_ or the German deutsche mark _DM_.
New values can be added without recompiling the application.
A code can have an optional validity period or simply a flag stating it is active or not.
To guaranty consistency with exported datasets, a code format shall never be deleted, only be disabled.
Code instances are immutable objects.

[NOTE]
====
You can smooth your transition from enumeration types to reference codes.
Extend your enumeration types with the _Code_ interface.

Now you can transform your code to support generic reference codes and make your application more dynamic to domain model changes.
====

[plantuml,bus-codes-uml,svg]
....
@startuml

interface Code {
    int id()
    String code()
    boolean isEnabled()
}

class CodeType <T extends Code> {
    Class<T> clazz()
    List<T> codes()
    List<T> activeCodes()
    List<T> inactiveCodes()
    Optional<T> findCode(int id)
    Optional<T> findCode(String code)
}

class CodeImp {}

CodeImp <|-- Code

@enduml
....

== Core

== Entity

An entity and all subclasses have a set of attributes present in any CSV file.

oid::
object identifier of the entity instance as the string representation of a 64 bits long. The value is mandatory.
id::
identifier of the entity instance as a string. The value is optional.
name::
human readable name of the entity instance as a string. The value is optional.
text::
human readable description of the entity instance as a long string. The value is optional.
fromDate::
start date when the entity instance is active. The value is optional.
toDate::
end date when the entity instance is active. Upon end date, the entity should be read-only and no more editied in the system. The value is optional.

[plantuml,bus-core-uml,svg]
....
@startuml

interface HasId {
    String id()
    String name()
}

interface HasOid {
    long oid()
}

interface HasTags {}

interface HasComments {}

interface HasOwner {}

HasOid <|.. HasOwner

interface Entity {
    + String text()
    + LocalDate fromDate()
    + LocalDate toDate()
}

HasOid <|.. Entity
HasId <|.. Entity
HasTags <|.. Entity
HasComments <|.. Entity

abstract class EntityImp {}

EntityImp *-- Tag : tags
EntityImp *-- Comment : comments

Entity <|.. EntityImp

class Address << (R,orchid) >>

class Tag <<record>>

class Comment {}

Comment *-- Tag : tags

class EmailAddress << (R,orchid) >>

@enduml
....

== Customer Relationship Model CRM

[plantuml,bus-crm-uml,svg]
....
@startuml

class BankConnection << (R,orchid) >> {
    String iban
    String bic
    String institute
}

class CrmEntity {}

HasTags <|.. CrmEntity

class LegalEntity {}

CrmEntity <|.. LegalEntity

class NaturalEntity {}

CrmEntity <|.. NaturalEntity

class Employee {}

Employee o-- NaturalEntity
Employee o-- LegalEntity


@enduml
....

== Invoices

=== Concepts

Invoices define a business bounded domain as defined in domain driven design approach.
They are not constrained through external entities such as products, contracts or legal entities.
External entities can provide hints to streamline the creation of regular invoices.
The invoice product identifier is available as an external identifier to the product bounded domain.
Similar identifiers are available for legal entities.

VAT rates are defined within a product definition.
Therefore, different VAT rates require different product definitions.
For example in Switzerland a service company has two VAT rates.
One for regular services and one for services exempted from VAT taxes.

The currency is defined at the invoice level meaning all invoice items and subtotals should use the same currency.

=== Archiving

An invoice contains all the information to create a legally binding document and hove no dependencies to external systems.
Invoices should have a unique identifier for accounting purposes.
A good practice is to use the identifier as part of the archived file to streamline traceability.
Invoices can be stored in a database, exported as a PDF file or as a JSON file.
The PDF file is human readable and adequate for document archiving and legal auditing.
The JSON file is an adequate archive format which can digitally be processed.

[plantuml,bus-invoice-uml,svg]
....
@startuml

package net.tangly.bus.crm {
    class LegalEntity {}

    class BankConnection << (R,orchid) >> {
        String iban
        String bic
        String institute
    }

    class Contract {}
}

package net.tangly.bus.invoices {
class Product << (R,orchid) >> {
    String productId
    String description
    BigDecimal unitPrice
    String unit
    BigDecimal vatRate
}

class Invoice {
    String id
    String contractId
    LocalDate deliveryDate
    LocalDate invoicedDate
    LocalDate dueDate
    Currency currency
    String text
    String paymentConditions
}

note right: contractId is the identifier to\nthe contract instance in the CRM package

Invoice *-- InvoiceLine : lines
Invoice o--> LegalEntity : invoicingEntity
Invoice o--> LegalEntity : invoicedEntity
Invoice *--> BankConnection : invoicingConnection

interface InvoiceLine {}

class InvoiceItem << (R,orchid) >> {}

InvoiceLine <|.. InvoiceItem

InvoiceItem o-- Product : product

class Subtotal << (R,orchid) >> {}

InvoiceLine <|.. Subtotal
}

@enduml
....

== Ledger

[plantuml,bus-ledger-uml,svg]
....
@startuml

class AccountEntry {}

class Transaction {}

class Account {}

class Ledger {}

Ledger *-- Account : accounts
Ledger *-- Transaction : transactions

@enduml
....

== Products

[plantuml,bus-product-uml,svg]
....
@startuml

class Assignment {}

class Effort {}

class Project {}

@enduml
....

