---
linkTitle: "01 Introduction"
weight: 10
date: 2023-01-01
---

[[section-introduction-and-goals]]
== Introduction and Goals

The open source _tangly OS ERP_ is a showcase for modern Java software development in an agile context.

The application shall be used to run a software engineering consulting boutique.
This benchmark is the proof the solution is usable in an economical context.

No expectations currently exist to ramp up the solution to a full-fledged enterprise resource planning system.

=== Requirements Overview

=== Quality Goals

Legibility::
The application is an example of modern java software engineering based on domain-driven design.
It is used as an example in teaching and coaching.
Maintainability::
The solution shall regularly be updated to current technical stacks and library versions.
The effort for the upgrades shall be reasonable.

=== Stakeholders

[cols="1,3",options="header"]
|===
|Role                 |Expectations
| Product Developer   | Fill work activities for invoicing purposes
| Product Responsible | Generate monthly reports and invoicing
| Controller          | Track the invoiced work agains the contract
| Marketing           | Have an overview of all product development for a customer
| Human Resources     | Can generate salary related forms
| Sponsor ERP         | A usable ERP to run the company daily business on it
|===
