---
title: "Readme"
date: 2019-05-01
weight: 10
---

= Commons Libraries

image:https://img.shields.io/badge/license-Apache%202-blue.svg[Apache License 2.0]
image:https://img.shields.io/maven-central/v/net.tangly/commons.svg[Maven Central]
https://javadoc.io/doc/net.tangly/commons[image:https://javadoc.io/badge2/net.tangly/commons/javadoc.svg[javadoc]]
image:https://img.shields.io/bitbucket/pipelines/tangly-team/tangly-os.svg[Bitbucket Pipelines]
image:https://img.shields.io/sonar/https/sonarcloud.io/tangly-os-at-tangly.net/coverage.svg[Sonar Coverage]
image:https://img.shields.io/bitbucket/issues-raw/tangly/tangly-os.svg[Bitbucket open issues]

== Purpose

A behavior-driven development library that provides a custom extension based on the JUnit 5 Jupiter Extension Model.
This library can be used to create and run stories and behaviors as BDD specification tests.

The library is a developer-first approach.
Developers write acceptance tests to validate the functions they have implemented.
The generated report provides a living documentation of the features and allows customers to validate the acceptance criteria.

The library is compact and integrated with JUnit 5 without disrupting TDD approaches and continuous integration pipelines.

== Download and Documentation

The library can be included in Maven as

[source,xml]
----
    <dependency>
      <groupId>net.tangly</groupId>
      <artifactId>commons</artifactId>
      <version>0.2.7</version>
    </dependency>
----

The library can be included in Gradle as

[source,groovy]
----
    implementation "net.tangly:commons:0.2.7"
----

The documentation can be found under https://blog.tangly.net/docs/commons/[Commons documentation]

For any further question and discussion, you can use the forum https://groups.google.com/g/tangly-os-components[tangly-OS-Components]

== Contribution

You are welcome to contribute to the product with pull requests on Bitbucket.
You can download the source files from the https://bitbucket.org/tangly-team/tangly-os.git[bitbucket git repository] and build the library with the provided gradle configuration file.

If you find a bug or want to request a feature, please use the https://bitbucket.org/tangly-team/tangly-os/issues[issue tracker].

== License

The source code is licensed under https://www.apache.org/licenses/LICENSE-2.0[Apache license 2.0].

The documentation and examples are licensed under https://creativecommons.org/licenses/by/4.0/[Creative Common (CC Attribution 4.0 International)].

== Awesome Sponsors and Developers

Corporate sponsors are

* https://www.tangly.net[tangly llc]

Individual developers are

* https://linkedin.com/in/marcelbaumann[Marcel Baumann]
