---
title: "Readme"
date: 2019-05-01
weight: 10
---

= Commons Libraries
:ref-groupId: net.tangly
:ref-artifactId: commons

image:https://img.shields.io/badge/license-Apache%202-blue.svg[Apache License 2.0]
image:https://img.shields.io/maven-central/v/{ref-groupId}/{ref-artifactId}[Maven Central]
https://javadoc.io/doc/{ref-groupId}/{ref-artifactId}[image:https://javadoc.io/badge2/{ref-groupId}/{ref-artifactId}/javadoc.svg[javadoc]]
image:https://github.com/tangly-team/tangly-os/actions/workflows/workflows.yml/badge.svg[build]
image:https://img.shields.io/github/issues-raw/tangly-team/tangly-os[issues]
image:https://img.shields.io/github/discussions/tangly-team/tangly-os[discussions]


== Purpose

A behavior-driven development library that provides a custom extension based on the JUnit 5 Jupiter Extension Model.
This library can be used to create and run stories and behaviors as BDD specification tests.

The library is a developer-first approach.
Developers write acceptance tests to validate the functions they have implemented.
The generated report provides a living documentation of the features and allows customers to validate the acceptance criteria.

The library is compact and integrated with JUnit 5 without disrupting TDD approaches and continuous integration pipelines.

== Download and Documentation

The library can be included in Maven as

[source,xml]
----
    <dependency>
      <groupId>net.tangly</groupId>
      <artifactId>commons</artifactId>
      <version>0.2.7</version>
    </dependency>
----

The library can be included in Gradle as

[source,groovy]
----
    implementation "net.tangly:commons:0.2.7"
----

The documentation can be found under {ref-tangly-blog-url}/docs/commons/[Commons documentation].

For any further questions, you can use the forum https://github.com/orgs/tangly-team/discussions[tangly-Discussions].
