version: 2
updates:
    -   package-ecosystem: "gradle"
        directory: "/"
        schedule:
            interval: "monthly"
        rebase-strategy: "disabled"

    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "monthly"
        rebase-strategy: "disabled"

