ifndef::imagesdir[:imagesdir: ./pics]

== User Manual

=== Idea

The tangly services ERP provides the functionalities to manage a service company offerings and legal documents.

The first customer ever using the application is https://www.tangly.net[tangly llc] company.
The company is an agile consulting and Java stack boutique organization.

A service company has no inventory, production, or logistics departments.

A service company has a strong focus on customers, products, projects and associcated efforts.
Cashfflow is dictated by the timely invoicing of performed activities.
The cash drain is mainly salaries and social costs.

=== Products

Collaborators can be assigned to projects.
They document their activities in time sheets describing the performed efforts.

Efforts are written down in a YAML file for each day, and each assignment.
The assignment uniquely identifies the product and the collaborator At most one effort shall be recorded per day and per assignment.

THe efforts are imported through the user interface.

[plantuml,effort-import,svg,align="center"]
....
@startsalt
{^"Import Effort Files"
{+
Selected Files
.
.
"               "
} | *

  []  Overwrite

  [Cancel] | [  OK   ]
}
@endsalt
....

Efforts are reported per collaborator, assignement and date interval.

[plantuml,effort-report,svg,align="center"]
....
@startsalt
{
  Assignement | "//Assignement OID//"
  Project     | "//Project ID//"
  Collaborator| "//Collaborator ID//"
  ContractId  | ^ContractId^
  From        | "2020-01-01"
  To          | "2020-01-31"
  ReportName  | "2020-01-johndoe-contractId"

  [Cancel] | [  OK   ]
}
@endsalt
....
