image: openjdk:18

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME=`pwd`/.gradle
  - export GRADLE_USER_HOME

build:
  stage: build
  script:
      - ./gradlew build net.tangly.erp.ui:installDist net.tangly.erp.ui:installShadowDist -Pvaadin.productionMode
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
    artifacts:
      paths:- net.tangly.erp.ui/build/distributions/*.zip
