image: eclipse-temurin:20

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME

build:
  stage: build
  script:
      - ./gradlew build net.tangly.erp.ui:installDist net.tangly.erp.ui:installShadowDist -Pvaadin.productionMode
  artifacts:
      paths:
          - net.tangly.erp.ui/build/distributions/*.zip
      expire_in: 2 week
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
