== tangly OS Components

The _tangly_ open source components are a set of open source libraries released under Apache 2.0 licence and are available through maven central.
The components are

* link:net.tangly.apps/readme.adoc[_APPS_] Vaadin user interface and REST services application library
* link:net.tangly.bdd/readme.adoc[_BDD_] behavior driven development library
* link:net.tangly.commons/readme.adoc[_COMMONS_] commons library
* link:net.tangly.core/readme.adoc[_CORE_] core library Core business abstractions such as address, bank connection, and legal entity are provided.
* link:net.tangly.dev/readme.adoc[_DEV_] development tools library
* link:net.tangly.fsm/readme.adoc[_FSM_] hierarchical finite state machine library.
The library also provides an actor abstraction and Java-based event bus.
* link:net.tangly.gleam/readme.adoc[_GLEAM_] declarative model transformation frameworks library.
Approaches for TSV and JSON representations are available.
* link:net.tangly.ui/readme.adoc[_UI_] Vaadin user interface library
* link:net.tangly.ui/readme.adoc[_WEB_] Web utilities library
* ERP Components
** link:net.tangly.erp.crm/readme.adoc[_ERP CRM_] customer relations management business components library
** link:net.tangly.erp.invoices/readme.adoc[_ERP INVOICES_] invoices business components library
** link:net.tangly.erp.ledger/readme.adoc[_ERP LEDGER_] ledger business components library
** link:net.tangly.erp.products/readme.adoc[_ERP PRODUCTS_] products business components library
** link:net.tangly.erp.shared/readme.adoc[_ERP SHARED_] shared business components library
** link:net.tangly.erp.ui/readme.adoc[_ERP UI] ERP application with a set of bounded domains with Vaadin user interface

The documentation is located under https://blog.tangly.net/[tangly-team].

The *primary repository* is hosted under GitHub https://github.com/marcelbaumann/tangly-os.git[tangly OS GitHub].

A mirror is also hosted under GitLab https://gitlab.com/marcelbaumann/tangly-os[tangly OS GitLab].
A legacy mirror is also hosted under BitBucket https://bitbucket.org/tangly-team/tangly-os.git[tangly OS BitBucket].

The issue tracker for errors, improvements, and corrections is https://github.com/tangly-team/tangly-os/issues[tangly OS issues].

For any further questions, you can use the forum https://github.com/orgs/tangly-team/discussions[tangly-Discussions].

We are experimenting with the most current versions of components, libraries and JDK.
The components are stored in a single git repository and are build using a multi-modules gradle build script.

== Contribution

You are welcome to contribute to the product with pull requests on {ref-github}.
You can download the source files from the https://github.com/tangly-team/tangly-os.git[GitHub git repository].
Build the library with the provided gradle configuration file.

If you find a bug or want to request a feature, please use the https://github.com/tangly-team/tangly-os/issues[issue tracker].

== License

The source code is licensed under https://www.apache.org/licenses/LICENSE-2.0[Apache license 2.0].

The documentation and examples are licensed under https://creativecommons.org/licenses/by/4.0/[Creative Common (CC Attribution 4.0 International)].

== Compile the product

You shall have access to a https://git-scm.com/[Git] installation to clone the repository and download the files.
You must install https://openjdk.org/install/index.html[JDK] version 22 to compile the source code.
The https://gradle.org/[Gradle] build file can be triggered without any supplemental installation with

[source,shell]
----
./gradlew build
----

The first run will take time because all dependencies will be downloaded from Maven repositories.
The next compilations will be much faster.
Ensure you have enough bandwidth to provide a smooth experience.

All development activities are performed with probably the best Java IDE IntelliJ IDEA.

== DevOps Activities

These instructions are for project committers.

The project is hosted on:

[source,console]
----
git add remote origin             git@github.com:tangly-team/tangly-os.git               <1>
git add remote origin-gitlab      git@gitlab.com:marcelbaumann/tangly-os.git             <2>
git add remote origin-bitbucket   git@bitbucket.org:tangly-team/tangly-os.git            <3>
----
<1> primary git repository due to the excellent support for static websites.
<2> secondary git repository.
<3> historical git repository missing support for {ref-asciidoc} and static websites.
_The educational repository of the technical university of Lucerne was removed after their gitlab server was compromised._

If you create a new remote repository, you can populate it with the following commands.

[source,console]
----
git remote add origin <repository-git-url>                                               <1>
git push --set-upstream origin --all                                                     <2>
git push --set-upstream origin --tags                                                    <3>
----

<1> Add the remote repository to your local git configuration.
<2> Push the whole content of the local repository to the remote repository.
<3> Push all branches to the remote repository.

=== CI/CD/CD

GitHub::
. Automated as build script
GitLab::
. Automated as build script
BitBucket::
. Go to the https://bitbucket.org/tangly-team/tangly-os/commits/[Commits]
. Select the commit you want to deploy
. On the displayed screen select the _Run pipeline_ operation.
You are presented with a selection of deployment options.
The variable _BB_AUTH_STRING_ is defined through _REPOSITORY-OWNER-NAME_:_APP-PASSWORD_.
The continuous deployment is a manual step to limit the usage of pipeline minutes and diminish associated costs.

== Contributions

You are welcome to contribute to the product.
Participate in https://github.com/orgs/tangly-team/discussions[discussions] or create https://github.com/tangly-team/tangly-os/issues[issues] on GitHub.

You can download the source files from the https://github.com/tangly-team/tangly-os[Open Source GitHub Repository].

Build the library with the provided Gradle configuration.

If you find a bug or want to request a feature, please use https://github.com/tangly-team/tangly-os/issues[issue tracker].

== License

The source code is licensed under https://www.apache.org/licenses/LICENSE-2.0[Apache license 2.0].

The documentation and examples are licensed under https://creativecommons.org/licenses/by/4.0/[Creative Common (CC Attribution 4.0 International)].

== Awesome Sponsors and Developers

Corporate sponsors are:

* https://www.tangly.net[tangly llc]

Individual developers are:

* https://linkedin.com/in/marcelbaumann[Marcel Baumann]
* https://linkedin.com/in/junghana/[Alexandra Junghans]
