---
title: "ERPUI-001: Markdown for all Text Fields"
LinkTitle: "Markdown Support"
date: 2021-06-01
weight: 1
---

== ERPUI-001 Markdown for all Text Fields

Date: 2021-06-01

=== Status

Implemented

=== Context

Markdown is a well-establish approach to write rich text documentation or comments.
The casual user can learn and use the notation without excessive effort.
The legibility and professional appearance of Markdown texts are markantly higher than plain text.
Markdown is an open standard and used in various environments and tools.

=== Decision

All texts and comments in the ERP components shall use Markdown notation to improve legibility.

Alternatives would be proprietary formats such as Microsoft Word or more sophisticated notations such as Asciidoc.
Our open source approach to product development rejects any propriatary formats.
Asciidoc is a very powerful and successful format.
The associated complexity for the users is probably an overkill for casual users of our product.

Text and comments in our system should have a limited length complexity.
Markdown is an optimal balance between expression power and ease of use.

=== Consequences

Markdown is backward compatible with text fields.
No migration of existing records is needed.

The user interface components shall be extended to support a Markdown visualiation and editing component.
Vaadin currently does not provide native support for Markdown.
The tangly-os components will be extended to provide such a component until Vaadin supports in the future such an approach.
