---
title: "ERP Design"
date: 2020-06-01
weight: 50
---
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:revnumber: v0.1
:revdate: 2020-05-31
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0

== ERP Design

=== Context

[plantuml, context-diagram-erp, svg]
....
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(salesperson, "Sales Engineer")
Person(accountant, "Accountant")
Person(manager, "Manager")

System_Boundary(c1, "tangly ERP") {
  Container(ledger_app, "Ledger", "Vaadin App", "Accounting System")
  Container(crm_app, "CRM", "Vaadin App", "Customer Relationship System")
  Container(analytics_app, "Analytics", "Vaadin App", "Analytics System")
  ContainerDb(storage, "Storage", "TSV and JSON Files", "Stores application data in TSV / JSON files")
}

System_Ext(email, "Gmail")
System_Ext(accounting, "Banana")
System_Ext(contacts, "Contacts")

Rel(salesperson, crm_app, "Uses", "https")
Rel(manager, crm_app, "Uses", "https")
Rel(accountant, ledger_app, "Uses", "https")
Rel(manager, analytics_app, "Uses", "https")

Rel(analytics_app, ledger_app, "Visualizes")
Rel(analytics_app, crm_app, "Visualizes")
Rel_Neighbor(crm_app, storage, "Reads from and writes to", "sync, JDBC")
Rel_Back_Neighbor(storage, ledger_app, "Reads from and writes to", "sync, JDBC")


Rel(ledger_app, accounting, "Gets transactions", "TSV")
Rel(crm_app, contacts, "Gets person photos", "VCard")
Rel(crm_app, email, "Gets emails", "IMAP")

@enduml
....

=== Persistence

==== Folder Structure

Files are written in italics font, folders are written in bold font.
Examples with content are provided for each file type as test resources.
These resources are available in the git repository.

[plantuml, folder-structure-erp, svg]
....
@startuml
    salt
    {
        {T
        + **crm**
        ++ //actitivites.tsv//       | tab separated representation of all activities of the company
        ++ //comments.tsv//          | tab separated representation of all comments defined in other entities
        ++ //contracts.tsv//         | tab separated representation of all contracts of the company
        ++ //employees.tsv//         | tab separated representation of all employees of the company
        ++ //interactions.tsv//      | tab separated representation of all interactions of the company
        ++ //legal-entities.tsv//    | tab separated representation of all legal entities of the company
        ++ //natural-entities.tsv//  | tab separated representation of all natural entities of the company
        ++ //subjects.tsv//          | tab separated representation of all subjects of the company
        ++ **vcards**
        +++ //john-doe.vcard//
        +++ ...
        + **invoices**               | contains all invoices grouped by issued date year
        ++ //products.tsv//          | tab separated representation of all products of the company
        ++ **2018**                  | all invoices issued in year 2018
        +++ //2018-01-01-invoice-x.json//
        +++ ...
        + **ledger**                | contains the ledger structure and the transactions per period
        ++ //swiss-ledger.tsv//
        ++ //2019-period.tsv//
        ++ //2020-period.tsv//
        ++ ...
        + **reports**               | the report files are generated through the ERP application
        ++ **invoices**
        +++ **2018**
        ++++ //2018-01-01-invoice-x.pdf//
        ++++ ...
        ++ **ledger**
        +++ //2019-ledger.pdf//
        +++ //2020-ledger.pdf//
        +++ ...
        }
    }
@enduml
....

=== Entity Abstraction

The entity abstraction has five kinds of properties

Simple Properties:: are all displayed in a form part of a _properties_ tab for visualization or editing.
Comments:: are displayed as a CRUD Grid - Form component part of a _comments_ tab for visualization or editing following CRUD approach.
Tags:: are displayed as a CRUD Grid - Form component part of a _tags_ tab for visualization or editing following CRUD approach.
The tag registry provides support for legible _namespaces_, _tag names_, and if defined _values_.
One-to-One Relations:: To be written
One-to-Many Relations:: To be written

=== CRUD Forms

CRUD forms are programmatically defined to offer full content and layout control to the developer.
The programmer populates a form layout and provides it to the CRUD class.
The CRUD class handles the buttons of the form and associated actions.
Callbacks are provided to inform the entity form class defining the form layout if the user accepted or canceled his changes in the form.

==== Crud List View and Details Form

[plantuml, crud-view, svg]
....
@startuml

interface SelectedItemListener<T> << (V,orchid) >> {}

interface HasIdView<T> {}

interface CrudForm<T> {}

class Crud<T> {}
VerticalLayout <|-- Crud
SelectedItemListener <|-- Crud

abstract class EntitiesView<T> {}
Crud <|-- EntitiesView
CrudForm <|-- EntitiesView

abstract class InternalEntitiesView<T extends NamedEntity> {}
EntitiesView <|-- InternalEntitiesView
HasIdView <|-- InternalEntitiesView

@enduml
....
