---
title: "ERP Design"
date: 2020-06-01
weight: 50
draft: false
---
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:revnumber: v0.1
:revdate: 2020-05-31
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0

== ERP Design

=== Context

[plantuml, context-diagram-erp, svg]
....
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(salesperson, "Sales Engineer")
Person(accountant, "Accountant")
Person(manager, "Manager")

System_Boundary(c1, "tangly ERP") {
  Container(ledger_app, "Ledger", "Vaadin App", "Accounting System")
  Container(crm_app, "CRM", "Vaadin App", "Customer Relationship System")
  Container(analytics_app, "Analytics", "Vaadin App", "Analytics System")
  ContainerDb(storage, "Storage", "TSV and JSON Files", "Stores application data in TSV / JSON files")
}

System_Ext(email, "Gmail")
System_Ext(accounting, "Banana")
System_Ext(contacts, "Contacts")

Rel(salesperson, crm_app, "Uses", "https")
Rel(manager, crm_app, "Uses", "https")
Rel(accountant, ledger_app, "Uses", "https")
Rel(manager, analytics_app, "Uses", "https")

Rel(analytics_app, ledger_app, "Visualizes")
Rel(analytics_app, crm_app, "Visualizes")
Rel_Neighbor(crm_app, storage, "Reads from and writes to", "sync, JDBC")
Rel_Back_Neighbor(storage, ledger_app, "Reads from and writes to", "sync, JDBC")


Rel(ledger_app, accounting, "Gets transactions", "TSV")
Rel(crm_app, contacts, "Gets person photos", "VCard")
Rel(crm_app, email, "Gets emails", "IMAP")

@enduml
....

=== Entity Abstraction

The entity abstraction has five kinds of properties

Simple Properties:: are all displayed in a form part of a _properties_ tab for visualization or editing.
Comments:: are displayed as a CRUD Grid - Form component part of a _comments_ tab for visualization or editing following CRUD approach.
Tags:: are displayed as a CRUD Grid - Form component part of a _tags_ tab for visualization or editing following CRUD approach.
The tag registry provides support for legible _namespaces_, _tag names_, and if defined _values_.
One to One Relations:: To be written
One to Many Relations:: To be written

=== CRUD Forms

CRUD forms are programmatically defined to offer full content and layout control to the developer.
The programmer populates a form layout and provides it to the CRUD class.
The buttons of the form and associated actions are handled by the CRUD class.
Callbacks are provided to inform the entity form class defining the form layout if the user accepted or cancelled his changes in the form.