---
title: "Developer Guide UI"
date: 2020-06-30
weight: 40
draft: false
---
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0
:stem:

== Developer Guide Commons UI

=== Develop ERP Application

==== Run From Command Line

To run quickly from the command-line in development mode:

[source,bash]
----
./gradlew run <1>
----
<1> Your app will be running on http://localhost:8080.

==== Run From IDE

* Run _./gradle vaadinPrepareFrontend_ in the project, to configure Vaadin for npm mode.
* Run/Debug the EmbeddedJetty class as an application (run the _main()- method).
The app will use npm to download all javascript libraries (will take a long time) and will start in development mode.
Your app will be running on http://localhost:8080.

If in trouble you can find and kill the server on a specific port address, here 8080 with the following commands.

[source,bash]
----
lsof -i :8080 | grep LISTEN <1>
ps -ef pid
kill pid <2>
----
<1> to get the pid of process using the port 8080
<2> kill the process using port 8080

=== Deploy ERP Application

==== Packaging for production

To package in production mode:

./gradlew build -PproductionMode=true
The project packages itself as a zip file with dependencies.
The file is in build/distributions/net.tangly.ui-X.Y.Z.zip

==== Running in production mode

To build and run the zip file:

[source,bash]
----
./gradle build -PproductionMode=true
cd build/distributions/
unzip net.tangly.ui-X.Y.Z.zip
cd net.tangly.ui-X.Y.Z/bin
export NET_TANGLY_UI_OPTS=--enable-preview <1>
./net.tangly.ui-X.Y.Z <2>
----
<1> enables preview mode for the JVM to support preview features
<2> head to localhost:8080/

If you do not have node installed in your CI environment, you can use Vaadin plugin to download node.js for you beforehand:

[source,bash]
----
./gradlew clean vaadinPrepareNode build -Pvaadin.productionMode
----

==== Running in Docker

To build and package this project as a docker image:

[source,bash]
----
./gradlew -PproductionMode=true
docker build --no-cache -t test/net.tangly.ui:latest .. <1>
docker run --rm -ti -p8080:8080 test/vaadin14-embedded-jetty <2>
----
<1> Docker will run the Dockerfile and build a docker image
<2> Run the image, head to localhost:8080/

=== Tips and Tricks

* The application works well with Google Chrome, Safari, and Firefox.
We have trouble with iPad Safari.
The menu bar and button bars are not always visible and scrolling is slow and bumpy.
* Using addAndExpand(Components ...) instead of add(Components ...) displays the button bar of a vertical component in iPad Safari.
