---
title: "User Guide UI"
date: 2019-06-30
weight: 30
---
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0
:stem:

== User Guide Commons Vaadin UI

=== Entity View

A domain entity shall be displayed and manipulated using the entity view.

A domain entity has an internal object identifier, an external identifier, a human-readable name, a temporaral period when the entity is active, and a textual description.

The entity can optionally have a set of tags and a list of comments.

[source,java]
----
public class MyEntityView extends EntityView<MyEntity> {
    static class MyEntityForm extends EntityForm<MyEntity, MyEntityView> {
        MyEntityForm(@NotNull MyEntityView parent) {
            super(parent);
        }
    }
}
----

=== Item View

=== Reflections

One key decision is that the user interface library does not require the use of annotations, interfaces, or inheritance in the business model.

Visualized entities are manipulated under different access rights.

* Readonly or full access

** Readonly access allow a user to view an entity and associated properties.
The update, delete and create operations are disabled.

** Full access allows a user to view, update, create and delete an entity and associated properties.

* Editable, immutable, or audited immutable entities

** Immutable entities or properties support view, create and delete.
The update operation is not available.
We avoid support for hybrid approach such as clone a new instance and delete an old one.
The semantics are often slightly awkward.

** Audited immutable entities or properties support view, and create.
Neither update nor delete operations are available to provide an audit trail.
Immutable instances can be added programmatically to provide an exhaustive audit trail.
