---
title: "Bounded Domain Invoice Model"
date: 2019-05-01
weight: 40
---

== Invoices Model

=== Concepts

Invoices define a business-bounded domain as defined in domain-driven design approach.
They are not constrained through external entities such as products, contracts or legal entities.
External entities can provide hints to streamline the creation of regular invoices.
The invoice article identifier is available as an external identifier to the article bounded domain.
Similar identifiers are available for legal entities.

The currency is defined at the invoice level, meaning all invoice items and subtotals should use the same currency.

==== VAT Rates

We initially stored VAT rates to the article abstraction.
Experience showed that VAT rates are subject to change and should be stored in the invoice line.

Each invoice line has a VAT rate and a computed VAT amount baed on the geographical location, time when the inovice line was created and the VAT rate.

The application does not try to provide a comprehensive VAT rate database and delegates the responsibility to the user to select the correct VAT rates.
Reasonable hints are provided through the user interface to streamline the selection process.

=== Archiving

An invoice contains all the information to create a legally binding document and hove no dependencies to external systems.
Invoices should have a unique identifier for accounting purposes.
A good practice is to use the identifier as part of the archived file to streamline traceability.
Invoices can be stored in a database, exported as a PDF file or as a JSON file.
The PDF file is human-readable and adequate for document archiving and legal auditing.
The JSON file is an adequate archive format that can digitally be processed.

[plantuml,bus-invoice-uml,svg]
....
@startuml

package net.tangly.core {
    class BankConnection << (R,orchid) >> {
        String iban
        String bic
        String institute
    }

   class Address << (R,orchid) >> {}
}

package net.tangly.erp.crmRealm {
    class LegalEntity {
        String id
}

    class Contract {
        String id
    }

package net.tangly.erp.invoices {
class Product << (R,orchid) >> {
    String productId
    String description
    BigDecimal unitPrice
    String unit
    BigDecimal vatRate
}

class invoiceLegalEntity << (R,orchid) >> {
    String id
    String name
    String vatNr
    EmailAddress email
}

invoiceLegalEntity *-- Address : address


note bottom: id of invoice legal entitty is also the identifier \nfor the legal entity instance in the CRM package.


class Invoice {
    String id
    String contractId
    LocalDate deliveryDate
    LocalDate invoicedDate
    LocalDate dueDate
    Currency currency
    String text
    String paymentConditions
}

note right: contractId is the identifier for the contract \ninstance in the CRM package.

Invoice *-- "*" InvoiceLine : lines
Invoice o--> "1" invoiceLegalEntity : invoicingEntity
Invoice o--> "1" invoiceLegalEntity : invoicedEntity
Invoice *--> BankConnection : invoicingConnection

interface InvoiceLine {}

class InvoiceItem << (R,orchid) >> {}

InvoiceLine <|.. InvoiceItem

InvoiceItem o-- Product : article

class Subtotal << (R,orchid) >> {}

InvoiceLine <|.. Subtotal
Subtotal o-- InvoiceLine

}

@enduml
....
