---
title: "OS 001: System Guava Removal"
linkTitle: "Guava Removal"
date: 2018-02-20
weight: 1
---
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0

== OS-001 Remove usage of Google Guava Library

Date: 2018-02-20

=== Status

Implemented

=== Context

The JDK 8 and JDK 9 provide better replacement methods for quite a lot of Guava functions.
New JDK are released every six months and provide regular improvements to the API.
These improvements make Guava functions more and more obsolete.

Guava is an external library of high quality but still an additional dependency in the application.
We always follow the rule to use language and standard library constructs over using external libraries.
Guava tries to support older JDKs and therefore do not use more modern approaches defined in new API versions.

The advantage is better integration, always synchronized with a new release of the JDK and no incompatibilities.
The drawback is sometimes a slightly more cumbersome syntax or solution.

=== Decision

All Guava usages shall be replaced by JDK standard function.
The main advantages are

. Current JDK versions provide own implementation e.g. in the Objects class
. Guava dependency is removed from our source code and compiled artifacts
. Guava is not optimized for idioms used in current JDK such as streams and extensive use of lambdas

=== Consequences

* Some operations are more complicated to implement because a solution is already provided in Guava
* We have the huge advantage to be able to use the current approaches provided in JDK and associated standard API.