---
title: "OS 003: Use Modern Java Constructs"
linkTitle: "Use Modern Java Constructs"
date: 2018-02-20
weight: 3
---
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0

= OS-003 Remove usage of Google Guava Library

Date: 2020-01-01

== Status

Implemented

== Context

JDK are released every six months to all Java developers.
Better approaches support clean code, less verbose source code and reduce programming errors.
These constructs shall be used in our modules as soon as they are released to the developers.

The advantage is better integration, always synchronized with the current release of the JDK and no incompatibilities.
The drawback is that our clients have to use the current JDK released version.

== Decision

We use the current released JDK and all constructs provided in this JDK.
We use preview features and incubating functionality present in this JDK.
The main advantages are

1. Current JDK versions provide performant and elegant implementation. See for example the record construct provided since JDK 14.
2. Source code is legible and has less errors.
3. Our developers are up to date with Java evolution and enjoy writing modern code.

== Consequences

* Clients are forced to use current JDK version.
* Tooling is more brittle because a lot of tool maintainers are late to adapt actual version of JDK.