---
title: "OS 006: Dependency Injection with Guice"
linkTitle: "DI Guice"
date: 2020-10-01
weight: 6
---

== OS-006 Dependency Injection with Guice

Date: 2018-02-20

=== Status

Implemented

=== Context

The modules provided as {ref-tangly} open source components are used in more complex applications.
These applications often use dependency injection frameworks to construct and initialize their instances.

=== Decision

Guice is selected as dependency injection framework.

. Guice is one of the industrial standard with Dagger and Sprint DI.
. Guicce supports JDK standard _@inject_ annotation used in other dependency frameworks.
. GUice supports the definition of modules to describe dependencies.
 The modules are also used as documentation mechanism.

Care will be taken to allow users to use a different dependency injection framework.

=== Consequences

* A dependency injection module shall be provided for each relevant module

=== Conventions

. Constructor injection is the preferred mechanism. In the long term it should be the only approach.
. Please avoid field injection as an injection approach.
