---
title: "SWAT Lecture"
date: 2019-05-01
weight: 30
---

== SWAT Lecture

=== Introduction

The software architecture and techniques _SWAT_ lecture conveys the basics of systematic agile design for a software architecture.
The approach is adequate for the problem of (agile architectural thinking) as well as methods of agile quality assurance.
Students apply the learnt principles of their semester or private software projects.

It is particularly suitable for students who are working on a larger software project at the same time.
The course with 3 https://en.wikipedia.org/wiki/European_Credit_Transfer_and_Accumulation_System[ECTS] was taught at Swiss technical universities during this and the last decade.
The themes are regularly updated to reflect actual trends and technical possibilities.

Slides and reference literature are in English and published under link:../#agile-software-architecture-and-techniques-lectures[Slides and Literature].

=== Description

stem:[2/3] of the lecture is the presentation of new concepts.
stem:[1/3] of the lecture is used to discuss the literature and support the students in the application of the concepts for their software project.

The reference books are cite:[building-evolutionary-architectures-2nd,building-evolutionary-architectures,refactoring].

Recommended books are cite:[clean-code,clean-coder,clean-architecture,clean-agile,clean-craftsmanship].

The basics of the domain-driven design approach are presented in the third part of the training
cite:[domain-driven-design,implementing-domain-driven-design,domain-driven-design-distilled].

[cols="2,3,5",frame=all,grid=all]
|====
|Lecture|Content|Details

|Lecture 1
|Why agile architecture and design?
a| - Introduction and administrative information
- Why is software architecture and design a needed discipline?
- Architecture Styles
- OOP Anti-Patterns
- _Setup environment for exercises and portfolio_

|Lecture 2
|Evolution of Software Architecture and Design over the last Decades
a|- Evolution of software architecture
- UML, RUP and TOGAF
- Agile approaches

|Lecture 3
|What is Agile Architecture?
a|- Agile architecture principles
- Developer vs Architects
- Domain-Driven Design _DDD_

|Lecture 4
|Agile Approaches with Scrum, eXtreme Programming, LeSS
a|- Architect roles
- Technology stacks
- DevOps impact on continuous integration _CI_, continuous delivery _CD_, and continuous deployment _CD_.

|Lecture 5
|Refactoring
a|- Why refactor?
- How to refactor?
- Test driven design _TDD_, acceptance test driven development _ATDD_
- Clean code and clean architecture

|Lecture 6
|Errors, Vulnerabilities, and Smells in Source Code
a|- Definition of smells and how to remove smells.
- Know the refactoring process with TDD.
- Evolve architecture to newer versions of programming languages or more modular architecture.

- Tools to detect non-quality
- Component quality

|Lecture 7
|Architecture of Components and Subsystems
a|- Patterns, idioms, paradigms
- SOLID principles
- Onion architecture
- Bounded domains

|Lecture 8
|Verify functional features
a|- Functional and non-functional requirements
- Verification of functional requirements
- TDD, ATDD, BDD approaches

|Lecture 9
|Validate Architecture Characteristics
a|- Non-functional requirement _NFR_ measurement
- Architecture Characteristics and fitness functions
- DevOps and DORA metrics
- Metrics and Automation
- Compliance and corporate governance

|Lecture 10
|Architecture Documentation
a|- Why document?
- Living documentation, architecture document record _ADR_
- Documentation as a managed source published in a static website


|Lecture 11
|Software Architectural Trends (1/2)
a|- Functional Programming
- Reactive Programming


|Lecture 12
|Software Architectural Trends (2/2)
a|- Security
- Monitoring and Auditing
- Realtime Data Warehouse _DWH_

|Lecture 13
|Domain-Driven Design Workshop
a| - Domain-Driven Development, ubiquitous language
- Bounded domains, entities, aggregates
- Event Storming
- Connection to modular monoliths and microservices based architecture
- Agile and DevOps affiliation

|Lecture 14
|Team and Technical Excellence for Architects
a|- Daily work of architects in agile environment
|====

=== Evolution

The teaching years 2023 and 2024 identified empirical facts:

- Slowly, the students have a better grasp of how digital products are created using agile approaches.
All students have training in design thinking and prototyping in the PTA lectures.
They have the opportunity to certify in design thinking through an IBM program.
- Basic knowledge of Scrum is provided through project management mandatory lecture.
Most students have a shallow understanding of Scrum values, artifacts and events.
The knowledge is insufficient for semester works or successful integration in a professional working environment.
The university is very reluctant to define concrete measures to improve knowledge transfer.
- Most students are fluent in programming.
Advanced concepts in Modern Java, Modern Python, or Modern Typescript are direly missing.
- Continuous delivery was trained in some lectures.
Experience in setting up a continuous integration, delivery, and deployment pipelines is missing.
The understanding of DevOps concepts is shallow.
The university has increased DevOps offering to improve the situation.
- The students welcome the emphasis of {ref-domain-driven-design} approaches.
The event storming workshop is a highlight of the lecture.

We tune the SWAT lecture to deepen understanding of:

- Deepen the understanding of architecture styles and approaches in an agile context.
- Provide concrete examples of domain-driven design tactical solutions based on the open source project tangly ERP.
The consequence is more emphasis on Modern Java, {ref-gradle}, {ref-git}, and {ref-github}.
We do not have the resources to provide source code examples in other technology stacks.
- Sharpen the semester project to better apply agile design principles.

=== References

bibliography::[]
