[versions]
jackson-version = '2.12.3'
jersey-version = '2.35'
javalin-version = '5.2.0'
jolt-version = '0.1.1'
junit-version = '5.9.2'
log4j2-version = '2.19.0'

microstream-version = '07.01.00-MS-GA'
mustang-version = '2.5.7'
openapi-version ="5.2.0"
vaadin-version = '23.3.6'
assertj-version = '3.24.2'

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin-version" }
spotbugs = "com.github.spotbugs:5.0.5"
sonarqube = "org.sonarqube:3.3"
sonatype = "org.sonatype.gradle.plugins.scan:2.2.2"
pitest = "info.solidsoft.pitest:1.7.0"
errorprone = "net.ltgt.errorprone:3.0.1"
jib = "com.google.cloud.tools.jib:3.2.0"
mannes = "com.github.ben-manes.versions:0.41.0"

[libraries]
annotations = "org.jetbrains:annotations:24.0.0"
antlr-st4 = "org.antlr:ST4:4.3.4"
apache-commons-cli = "commons-cli:commons-cli:1.5.0"
apache-commons-csv = "org.apache.commons:commons-csv:1.10.0"
apache-commons-codec = "commons-codec:commons-codec:1.15"
apache-commons-io = "commons-io:commons-io:2.11.0"

apache-log4j2-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j2-version" }
apache-log4j2-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j2-version" }
apache-log4j2-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j2-version" }

slf4j-simple = "org.slf4j:slf4j-simple:2.0.6"

apache-pdfbox = "org.apache.pdfbox:pdfbox:2.0.25"
arch-unit = "com.tngtech.archunit:archunit-junit5-api:1.0.1"

asciidoctorj-core = "org.asciidoctor:asciidoctorj:2.5.7"
asciidoctorj-pdf = "org.asciidoctor:asciidoctorj-pdf:2.3.4"
asciidoc-converter = "nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:1.0"

assertj = { module = "org.assertj:assertj-core", version.ref = "assertj-version" }
commonmark = "org.commonmark:commonmark:0.21.0"
eo-yaml = "com.amihaiemil.web:eo-yaml:5.2.1"
flyway = "org.flywaydb:flyway-core:9.14.1"
hsqldb = "org.hsqldb:hsqldb:2.7.1"
iban4j = "org.iban4j:iban4j:3.2.4-RELEASE"

ical4j-core = "org.mnode.ical4j:ical4j:3.2.1"
ical4j-vcard = "org.mnode.ical4j:ical4j-vcard:1.0.7"

google-libphonenumber = "com.googlecode.libphonenumber:libphonenumber:8.13.6"

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-version" }
jackson-parameters = { module = "com.fasterxml.jackson.module:jackson-module-parameter-names", version.ref = "jackson-version" }
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson-version" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-version" }

jakarta-mail = "com.sun.mail:jakarta.mail:2.0.1"
jbibtext = "org.jbibtex:jbibtex:1.0.20"
jimfs = "com.google.jimfs:jimfs:1.2"

#redoc is at /redoc and swagger is at /swagger, only supported in version 5.x
javalin = { module = "io.javalin:javalin", version.ref = "javalin-version" }
javalin-openapi-plugin = { module = "io.javalin.community.openapi:javalin-openapi-plugin", version.ref = "openapi-version" }
javalin-swagger-plugin = { module = "io.javalin.community.openapi:javalin-swagger-plugin", version.ref = "openapi-version" }
javalin-redoc-plugin = { module = "io.javalin.community.openapi:javalin-redoc-plugin", version.ref = "openapi-version" }

#Java 9 module compliant version of https://github.com/stleary/JSON-java
json-core = "com.guicedee.services:json:1.2.2.1"
json-validator = "com.networknt:json-schema-validator:1.0.77"
json-assert = "org.skyscreamer:jsonassert:1.5.0"
json-jolt-core = { module = "com.bazaarvoice.jolt:jolt-core", version.ref = "jolt-version" }
json-jolt-utils = { module = "com.bazaarvoice.jolt:jolt-utils", version.ref = "jolt-version" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-version" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-version" }

lanterna = "com.googlecode.lanterna:lanterna:3.1.1"
lombok = "org.projectlombok:lombok:1.18.26"
mustang-core = { module = "org.mustangproject:library", version.ref = "mustang-version" }
mustang-validator = { module = "org.mustangproject:validator", version.ref = "mustang-version" }

neo4j = "org.neo4j:neo4j:4.3.7"

qrbill = "net.codecrete.qrbill:qrbill-generator:3.0.7"

microstream-storage = { module = "one.microstream:microstream-storage-embedded", version.ref = "microstream-version" }
microstream-jdk8 = { module = "one.microstream:microstream-persistence-binary-jdk8", version.ref = "microstream-version" }
microstream-jdk17 = { module = "one.microstream:microstream-persistence-binary-jdk17", version.ref = "microstream-version" }

mockito = "org.mockito:mockito-junit-jupiter:5.1.1"

scribe = "com.github.scribejava:scribejava-apis:8.3.1"

vaadin-bom = { module = "com.vaadin:vaadin-bom", version.ref = "vaadin-version" }
vaadin-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin-version" }
vaadin-autocomplete = "com.vaadin.componentfactory:autocomplete:2.3.2"
vaadin-browser-storage = "org.vaadin.componentfactory:browserstorage:1.0.0"
vaadin-daterange = "com.vaadin.componentfactory:vcf-date-range-picker:4.0.0"
vaadin-tooltip = "com.vaadin.componentfactory:tooltip:1.3.7"
vaadin-pdfviewer = "org.vaadin.addons.componentfactory:vcf-pdf-viewer:2.7.0"

vaadin-socharts = "com.storedobject.chart:so-charts:3.1.3"
vaadin-signature = "de.f0rce.signaturepad:signature-widget:2.0.1"
vaadin-test = "com.github.mvysny.kaributesting:karibu-testing-v23:1.3.23"

vaadin-embedded-jetty = "com.github.mvysny.vaadin-boot:vaadin-boot:10.3"

[bundles]
test-deps = ["junit-api", "assertj", "mockito", "arch-unit"]
jackson-deps = ["jackson-databind", "jackson-parameters", "jackson-datatype", "jackson-jsr310"]
microstream-deps = ["microstream-storage", "microstream-jdk8", "microstream-jdk17"]
