[versions]
assertj-version = '3.24.2'
flyway-version = '10.3.0'
jackson-version = '2.12.3'
jersey-version = '2.35'
javalin-version = '5.6.3'
jolt-version = '0.1.1'
junit-version = '5.10.1'
log4j2-version = '2.20.0'
openapi-version = "5.6.3-2"
eclipsestore-version = '1.0.0'
mustang-version = '2.9.0'
vaadin-version = '24.3.0'

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin-version" }
spotbugs = "com.github.spotbugs:5.0.5"
sonarqube = "org.sonarqube:3.3"
sonatype = "org.sonatype.gradle.plugins.scan:2.2.2"
pitest = "info.solidsoft.pitest:1.7.0"
errorprone = "net.ltgt.errorprone:3.0.1"
jib = "com.google.cloud.tools.jib:3.2.0"
mannes = "com.github.ben-manes.versions:0.41.0"

[libraries]
annotations = "org.jetbrains:annotations:24.1.0"
antlr-st4 = "org.antlr:ST4:4.3.4"
apache-commons-cli = "commons-cli:commons-cli:1.5.0"
apache-commons-csv = "org.apache.commons:commons-csv:1.10.0"
apache-commons-codec = "commons-codec:commons-codec:1.16.0"
apache-commons-io = "commons-io:commons-io:2.11.0"

apache-log4j2-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j2-version" }
apache-log4j2-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j2-version" }
apache-log4j2-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j2-version" }

awaitility = "org.awaitility:awaitility:4.2.0"

slf4j-simple = "org.slf4j:slf4j-simple:2.0.9"

apache-pdfbox = "org.apache.pdfbox:pdfbox:3.0.1"
arch-unit = "com.tngtech.archunit:archunit-junit5-api:1.2.1"

asciidoctorj = "org.asciidoctor:asciidoctorj:2.5.10"
asciidoctorj-pdf = "org.asciidoctor:asciidoctorj-pdf:2.3.9"

assertj = { module = "org.assertj:assertj-core", version.ref = "assertj-version" }
eo-yaml = "com.amihaiemil.web:eo-yaml:5.2.1"

flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway-version" }
flywy-hsqldb = { module = "org.flywaydb:flyway-database-hsqldb", version.ref = "flyway-version" }

hsqldb = "org.hsqldb:hsqldb:2.7.2"
iban4j = "org.iban4j:iban4j:3.2.7-RELEASE"

ical4j-core = "org.mnode.ical4j:ical4j:3.2.1"
ical4j-vcard = "org.mnode.ical4j:ical4j-vcard:1.0.7"

google-libphonenumber = "com.googlecode.libphonenumber:libphonenumber:8.13.27"
google-protobuf = "com.google.protobuf:protobuf-java:3.24.3"

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-version" }
jackson-parameters = { module = "com.fasterxml.jackson.module:jackson-module-parameter-names", version.ref = "jackson-version" }
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson-version" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-version" }

jakarta-mail = "jakarta.mail:jakarta.mail-api:2.1.2"
eclipse-angus-mail = "org.eclipse.angus:angus-mail:2.0.2"

jbibtext = "org.jbibtex:jbibtex:1.0.20"
jimfs = "com.google.jimfs:jimfs:1.3.0"

#redoc is at /redoc and swagger is at /swagger, only supported in version 5.x
javalin = { module = "io.javalin:javalin", version.ref = "javalin-version" }
javalin-openapi-plugin = { module = "io.javalin.community.openapi:javalin-openapi-plugin", version.ref = "openapi-version" }
javalin-swagger-plugin = { module = "io.javalin.community.openapi:javalin-swagger-plugin", version.ref = "openapi-version" }
javalin-redoc-plugin = { module = "io.javalin.community.openapi:javalin-redoc-plugin", version.ref = "openapi-version" }

#Java 9 module compliant version of https://github.com/stleary/JSON-java
json-core = "com.guicedee.services:json:1.2.2.1"
json-validator = "com.networknt:json-schema-validator:1.1.0"
json-assert = "org.skyscreamer:jsonassert:1.5.0"
json-jolt-core = { module = "com.bazaarvoice.jolt:jolt-core", version.ref = "jolt-version" }
json-jolt-utils = { module = "com.bazaarvoice.jolt:jolt-utils", version.ref = "jolt-version" }

jsoup = "org.jsoup:jsoup:1.17.1"

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-version" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-version" }

lombok = "org.projectlombok:lombok:1.18.30"

measurement-api = "javax.measure:unit-api:2.2"
measurement-ri = "tech.units:indriya:2.1.3"

micrometer = "io.micrometer:micrometer-registry-prometheus:1.11.0"
micrometer-jmx = "io.micrometer:micrometer-registry-jmx:1.11.0"

mustang-core = { module = "org.mustangproject:library", version.ref = "mustang-version" }
mustang-validator = { module = "org.mustangproject:validator", version.ref = "mustang-version" }

qrbill = "net.codecrete.qrbill:qrbill-generator:3.2.0"

eclispsestore-storage = { module = "org.eclipse.store:storage-embedded", version.ref = "eclipsestore-version" }

mockito = "org.mockito:mockito-junit-jupiter:5.8.0"

scribe = "com.github.scribejava:scribejava-apis:8.3.1"

vaadin-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin-version" }
vaadin-pdfviewer = "org.vaadin.addons.componentfactory:vcf-pdf-viewer:2.8.0"

vaadin-embedded-jetty = "com.github.mvysny.vaadin-boot:vaadin-boot:12.2"
vaadin-socharts = "com.storedobject.chart:so-charts:3.2.4"
vaadin-test = "com.github.mvysny.kaributesting:karibu-testing-v23:2.1.0"

[bundles]
test-deps = ["junit-api", "assertj", "mockito", "arch-unit"]
jackson-deps = ["jackson-databind", "jackson-parameters", "jackson-datatype", "jackson-jsr310"]
microstream-deps = ["eclispsestore-storage"]
