---
title: "Readme"
date: 2019-05-01
weight: 10
---

= ERP User Interface Component
:ref-groupId: net.tangly.erp
:ref-artifactId: ui

image:https://img.shields.io/badge/license-Apache%202-blue.svg[Apache License 2.0]
image:https://img.shields.io/maven-central/v/{ref-groupId}/{ref-artifactId}[Maven Central]
https://javadoc.io/doc/{ref-groupId}/{ref-artifactId}[image:https://javadoc.io/badge2/{ref-groupId}/{ref-artifactId}/javadoc.svg[javadoc]]
image:https://github.com/tangly-team/tangly-os/actions/workflows/workflows.yml/badge.svg[build]
image:https://img.shields.io/github/issues-raw/tangly-team/tangly-os[issues]
image:https://img.shields.io/github/discussions/tangly-team/tangly-os[discussions]

== Purpose

The *tangly erp ui* bounded domain component provides regular business model abstractions for business applications written in Java.
The component is using records and requires *Java 17 or higher*.

*Try it out*.

== Download and Documentation

Include the library in your Maven configuration as:

[source,xml]
----

<dependency>
    <groupId>net.tangly.erp</groupId>
    <artifactId>ui</artifactId>
    <version>0.2.7</version>
</dependency>

----

Include the library in your Gradle configuration as:

[source,groovy]
----
    implementation "net.tangly.erp:ui:0.2.7"
----

The documentation can be found under {ref-tangly-blog-url}/docs/domains/ui/[Business documentation].

For any further questions, you can use the forum https://github.com/orgs/tangly-team/discussions[tangly-Discussions].

== Run as an Application

=== Run Locally with Gradle

The gradle script compiles, packages, and runs the application with an embedded web server. _Run from the project root_.

[source,shell]
----
    gradle run
----

The following end points are available:

- The application user interface is available at `http://localhost:8080/erp/`.
- The REST interfaces are available under `http://localhost:8080/erp/DOMAIN/ENTITY`.
An example is `http://localhost:8080/erp/rest/customers/natural-enitites`.
- The openAPI description file is available under `http://localhost:8080/rest/openapi.json`.
- The swagger server is serviced under `http://localhost:8080/rest/swagger`.

The reports are available under `http://localhost:8080/erp/reports/`.

=== Run locally as compiled application

You can build and run the generated Java Vaadin application locally. _Run from the project root_.

[source,shell]
----
  ./gradlew build installDist -Pvaadin.-Pvaadin.forceProductionBuild=true   <1>
  net.tangly.erp.ui/build/install/net.tangly.erp.ui/bin/net.tangly.erp.ui   <2>
----

=== Run locally as fatjar application

You can build and run the generated Java Vaadin application as fat jar locally. _Run from the project root_.

[source,shell]
----
  ./gradlew build installShadowDist -Pvaadin.productionMode                 <3>
  net.tangly.erp.ui/build/install/net.tangly.erp.ui-shadow/bin/net.tangly.erp.ui <2>
  java $JVM_OPTS -jar net.tangly.erp.ui/build/install/net.tangly.erp.ui-shadow/lib/net.tangly.erp.ui-all.jar <3>

----

* <1> The production mode parameter is mandatory.
Otherwise, the distribution frontend is not built, and the application cannot run without JavaScript build tools.
* <2> Head to \http://localhost:8080/erp/.
The default port is 8080, and the application starts with in-memory storage.
The environment variables are set in the run script.
* <3> Start the application with java command.
You are responsible to provide the JVM options as define below.

The JVM options to run the application are

[source,shell]
----
JVM_OPTS="--enable-preview --add-exports=java.base/jdk.internal.misc=ALL_UNNAMED \
          --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED -XX:+ShowCodeDetailsInExceptionMessages -Xmx256m"
----

=== Run in a Docker Image

The prerequisite is that the application was built locally for production mode as described above.
The first step is to build the Docker image with the provided configuration.
_Run from the project root_.

[source,shell]
----
  ./gradlew net.tangly.erp.ui:installDist -Pvaadin.productionMode   <1>
  docker login -u tanglyllc -p <password>                           <2>
  docker build -t tanglyllc/tangly-erp:latest net.tangly.erp.ui/    <3>
  docker push tanglyllc/tangly-erp:latest                           <4>
----

<1> Build the Java application and create a binary distribution of the application.
<2> Login into DockerHub with username and password.
<3> Generate a Docker image containing the binary application generated in the previous step.
<4> Push the Docker image to the repository.
Customers can retrieve the published Docker image and execute it in a container.

We currently push to https://hub.docker.com/[Docker Hub] repository.
The image is accessible unde https://hub.docker.com/r/tanglyllc/tangly-erp[tangly-erp Docker Image].

To run the built image use the following commands.

[source,shell]
----
  docker run --rm -ti -p 8080:8080 -e PORT=8080 -e m=true  -v /var/tangly-erp:/var/tangly-erp tanglyllc/tangly-erp:latest
----

The user under which the erp application shall not have root privileges.

The port of the application is configured through the port environment variable.
This approach is mandatory if the image is deployed in https://www.heroku.com/[Heroku].

=== Run in the Cloud

[CAUTION]
====
The deployment on the Heroku cloud was removed due to changes in the usage conditions of the platform.

Therefore, we do not deploy anymore our applications on Heroku.
====
