---
title: "Architecture Code Scene"
date: 2019-05-01
weight: 80
---
== Architecture Code Scene
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:revnumber: v0.1
:revdate: 2020-05-31
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0

=== Purpose

Agile development teams shall manage and diminish their technical debt. We provide instruments to increase the pay-off of refactoring measures. The
most relevant source code parts should be refactored first. But how can we identify them?

Git is the de facto standard for version management systems. Git contains the whole evolution story of our source code. We use this data to identify
areas under repetitive change or often needing fixing. In parallel the evolution of the source code hints us for complexity hotspots.

The three area of statistical data are combined to identify the most promising area for refactoring.
* History of commits reflecting the behavior and priorities of team members over time
* Evolution of source code artifacts reflecting changes in complexity and legibility
* Corrections of identified defects and their location identify non-quality hotspots

The provided tools extract the requested indicators and presents them graphically. The findings are used to support refactoring priorzsation.

=== Requirements

. Gather changes in the repository artifacts over a specified time interval
  .. the gathered data are date of change, author of change, number of added lines and of removed lines
  .. each file change is gathered
  .. only the version management system __git__ is supported
. Gather complexity metrics over source code artifacts - classes and packages - over a specified time interval
. Gather location and time when identified defects were fixed in the source code repository
  .. use the official conventions to identify a closed ticket in a commit comment


=== Modules, Packages, Classes and Files

[plantuml, architecture-code-scene-model, svg]
....
@startuml

class Commit {
  String comment
}

Class CommitItem
class Committer {
  String name
}

class RepositoryFile {
  String filename
  boolean test
}

class Project {
  String name
}

class Module {
  String qualifiedName
}

class Package {
  String qualifiedName
}

class Clazz {
  String qualifiedName
}

Commit "1" *-- "*" CommitItem
Commit o-- "1" Committer
RepositoryFile "1" o-- "*" CommitItem

Project o-- Module
Module "1" *--  "*" Package
Package "1" *-- "*" Clazz
Clazz o-- RepositoryFile

Project *-- "*" Committer
Project *-- "*" Commit

@enduml
....
