---
title: "Components Publication"
date: 2019-05-01
weight: 40
---

== Components Publication
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0

=== Regular Git Repository Update

. Push the changes to the Bitbucket repository
.. Verify the build job in the CI pipeline was successful
. Push the changes to the GitHub repository.
_The statistics for developer activities will be automatically updated._

=== Maven Central Publication

The following process is used to publish {ref-tangly} open source component on https://mvnrepository.com/repos/central[Maven Central].

. Publish artifacts of component with the script `uploadToMavenCentral.sh`.
Do not use the gradle task `gradle publishAllPublicationsToMavenRepository -Pmode=prod`.
Sonatype cannot handle parallel upload of multiple components and simply close the connections during upload (Status 2020-Q2).
.. Pre activity: test publishing with `gradle publishToMavenLocal`
.. Pre activity: check on bitbucket the product compile through the *CI* continuous integration pipeline
.. Post activity: *tag repository* on git to identify the version of the published packages.
The tag version semantic part *must* be the same as the package version on https://mvnrepository.com/repos/central[Maven Central]
The tag is of the form -{AcronymComponent}-MajorVersion-MinorVersion-PatchVersion-
.. Verify with `git tag label` and `git push origin --tags`
. Log into https://oss.sonatype.org/#welcome[Sonatype Maven Central Repository]
.. Go to https://oss.sonatype.org/#stagingRepositories[Staging Repositories]
.. Find your temporary repository at the end of list
.. Review the content of the repository
.. Close the repository -button on tool list-
.. Close stage is initiated and checks are performed.
If everything was fine the content is published.
.. Release the artifact -button on tool list-
. See <<website-publication>> to update the website

[CAUTION]
====
It takes up to one day until the component is visible in Maven Central website upon publication.

On the positive side, the last publications were performed in less than 30 minutes.
====

Below the dependencies between tangly open source components as defined in the multi-modules {ref-gradle} build file.

[plantuml,tangly-componentsDependencies,svg,svg-type="interactive"]
....
package net.tangly.bdd [[https://tangly-team.bitbucket.io/docs/bdd/]] {
}

package net.tangly.commons [[https://tangly-team.bitbucket.io/docs/commons/]] {
}

package net.tangly.core [[https://tangly-team.bitbucket.io/docs/core/]] {
}

package net.tangly.dev [[https://tangly-team.bitbucket.io/docs/dev/]] {
}
net.tangly.dev --> net.tangly.commons

package net.tangly.fsm [[https://tangly-team.bitbucket.io/docs/fsm/]] {
}

package net.tangly.gleam [[https://tangly-team.bitbucket.io/docs/gleam/]] {
}
net.tangly.gleam --> net.tangly.commons

package net.tangly.ports [[https://tangly-team.bitbucket.io/docs/ports/]] {
}

package net.tangly.ui [[https://tangly-team.bitbucket.io/docs/ui/]] {
}

package net.tangly.erp.crm [[https://tangly-team.bitbucket.io/docs/erp/crm]] {
}

package net.tangly.erp.invoices [[https://tangly-team.bitbucket.io/docs/erp/invoices]] {
}

package net.tangly.erp.ledger [[https://tangly-team.bitbucket.io/docs/erp/ledger]] {
}

package net.tangly.erp.products [[https://tangly-team.bitbucket.io/docs/erp/products]] {
}

package net.tangly.erp.shared [[https://tangly-team.bitbucket.io/docs/erp/shared]] {
}

package net.tangly.erp.ui [[https://tangly-team.bitbucket.io/docs/erp/ui]] {
}

....

==== Decisions

. The open source components are stored in a mono repository.
Each component is declared as a gradle module.
. We use de facto standard Git.
. We are hosted at https://bitbucket.org[bitbucket].
. The bitbucket repository is regularly synchronized with a GitHub mirror repository https://github.com/marcelbaumann/tangly-os.git[GitHub].

The synchronization is performed with the command

[source,shell]
----
git push --prune https://github.com/marcelbaumann/tangly-os.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/* <1>

git remote <2>

git push origin-bitbucket <3>
----
<1> Pushes the repository with all remotes, references and tags to GitHub specified repository
<2> List all remotes associated with this git repository
<3> Pushes the master branch to the _origin-bitbucket_ remote repository.
The push shall trigger the continuous integration pipeline

You must create a token for developer account to be able to push changes and trigger the CI pipeline.
The username is your account username The password is the generated token
footnote:[This is necessary if you have enabled two factors authentication.
The other approach is to generate a SSH key and perform all operations other SSH.].
Store it in a safe place.

==== Findings

. We needed to manually publish the public key on http://keys.gnupg.net[keys.gnupg.net]
. Gradle build file has a condition include to disable the signing plugin on the CI pipeline because keys and associated authentication are not available.
I decided not to upload private keys to https://bitbucket.org/[bitbucket].
See the documentation at the beginning of the Gradle build file for details.

IMPORTANT: Set the property if you want to sign the component artifacts and publish to Maven Central.

[#website-publication]
=== Website Publication

==== Configure asciidoctor

The new version of hugo support configuration of asciidoctor through config.toml therefore no manipulation of asciidoctor is needed.
As a bonus the file generated by PlantUml are created in the correct folder.
We still need to install the referenced packages.

[source,shell]
----
sudo gem install asciidoctor-diagram
sudo gem install asciidoctor-rouge
sudo gem install asciidoctor-html5s
sudo gem install asciimath
----

==== Create Website

The tangly open source components website is hosted https://tangly-team.bitbucket.io/[here].

Read the instructions in the asciidoctor script file under the scripts' folder.
Four scripts are provided to generate the Hugo static site with associated structure and theme.

. the script _initiateHugo.sh_ creates the layout of the site and retrieve the theme.
. the script _populateHugo.sh_ populates the site with our content.

Upon completion of local development you must start a local Hugo server and generate the indexing files for https://lunrjs.com/[lunr] search.
Before uploading the site stop the Hugo local server.

. the script _completeHugo.sh_ generates the static pictures and copy them to the static folder and publish the whole site on bitbucket.

Upon completion the site is published on the web for all.

==== Set JDK Version under macOS

Install regular Java JDK (Oracle or OpenJDK for example).
They will be located under _/Library/Java/JavaVirtualMachines_.

If using bash shell, add following commands to your .bash_profile.

[source,shell]
----
alias java15 = "export JAVA_HOME=`/usr/libexec/java_home -v 15`; java -version"
alias java11 = "export JAVA_HOME=`/usr/libexec/java_home -v 11`; java -version"
----

You can set the exact version such as _15.0.2_ to precisely select a JDK or set an overall version such as _15_ to select a generic version.

After restarting your terminal the command _java15_ will set JDK 15 to default JDK (if installed on your macOS).

The list of JDK can be found with

[source,shell]
----
/usr/libexec/java_home -V
----

==== Create Docker Distribution

Generate the ERP application as a production release.

[source, shell]
----
gradle install -DproductionMode=true <1>
gradle install -Pproduction
unzip ./build/distributions/net.tangly.erp.ui-<version>.zip <2>
docker build -t erp-docker . <3>
docker run -ti -p 8080:8080 erp-docker <4>
----
<1> Generates a production distribution stored under ./build/distributions
<2> Unzip the packed distribution because the docker base image does not contain unzip utility
<3> Build the docker image named _erp-docker_
<4> Run the docker image _erp-docker_ and map the image port to 8080
