---
title: "Components Publication"
date: 2019-05-01
weight: 40
---

== Components Publication
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0

=== Maven Central Publication

The following process is used to publish {ref-tangly} open source component on https://mvnrepository.com/repos/central[Maven Central].

. Publish artifacts of component with the script `uploadToMavenCentral.sh`.
 Do not use the gradle task `gradle publishAllPublicationsToMavenRepository -Pmode=prod`.
 Sonatype cannot handle parallel upload of multiple components and simply close the connections during upload (Status 2020-Q2).
.. Pre activity: test publishing with `gradle publishToMavenLocal`
.. Pre activity: check on bitbucket the product compile through the *CI* continuous integration pipeline
.. Post activity: *tag repository* on git to identify the version of the published packages.
 The tag version semantic part *must* be the same as the package version on https://mvnrepository.com/repos/central[Maven Central]
 The tag is of the form -{AcronymComponent}-MajorVersion-MinorVersion-PatchVersion-
.. Verify with `git tag label` and `git push origin --tags`
. Log into https://oss.sonatype.org/#welcome[Sonatype Maven Central Repository]
.. Go to https://oss.sonatype.org/#stagingRepositories[Staging Repositories]
.. Find your temporary repository at the end of list
.. Review the content of the repository
.. Close the repository -button on tool list-
.. Close stage is initiated and checks are performed.
 If everything was fine the content is published.
.. Release the artifact -button on tool list-
. See <<website-publication>> to update the website

[CAUTION]
====
It takes up to one day until the component is visible in Maven Central website upon publication.

On the positive side, the last publications were performed in less than 30 minutes.
====

The acronyms are (the current composite acronym is TANGLY_OS meaning all components are released)

* *BDD* behavior driven development library
* *BUS* business components library
* *COMMONS* commons library
* *DEV* development tools library
* *FSM* hierarchical finite state machine library
* *GLEAM* declarative model transformation frameworks library
* *PORTS* ports library
* *UI* Vaadin user interface library

Below the dependencies between tangly open source components as defined in the multi-modules {ref-gradle} build file.

[plantuml,tangly-componentsDependencies,svg,svg-type="interactive"]
....
package net.tangly.bdd [[https://tangly-team.bitbucket.io/docs/bdd/]] {
}
package net.tangly.bus [[https://tangly-team.bitbucket.io/docs/bus/]] {
}

package net.tangly.commons [[https://tangly-team.bitbucket.io/docs/commons/]] {
}

net.tangly.bus --> net.tangly.commons
package net.tangly.dev [[https://tangly-team.bitbucket.io/docs/dev/]] {
}

net.tangly.dev --> net.tangly.commons

package net.tangly.fsm [[https://tangly-team.bitbucket.io/docs/fsm/]] {
}

package net.tangly.gleam [[https://tangly-team.bitbucket.io/docs/gleam/]] {
}

net.tangly.gleam --> net.tangly.commons

package net.tangly.ports [[https://tangly-team.bitbucket.io/docs/ports/]] {
}

net.tangly.ports --> net.tangly.commons
net.tangly.ports --> net.tangly.bus
net.tangly.ports --> net.tangly.gleam

package net.tangly.ui {}
net.tangly.ui --> net.tangly.commons
net.tangly.ui --> net.tangly.bus
net.tangly.ui --> net.tangly.gleam
net.tangly.ui --> net.tangly.ports
....

==== Decisions

. The open source components are stored in a mono repository.
 Each component is declared as a gradle module.
. We use de facto standard Git.
. We are hosted at https://bitbucket.org[bibucket].
. The bitbucket repository is regularly synchronized with a github mirror repository https://github.com/marcelbaumann/tangly-os.git[github].

The synchronization is performed with the command

[code]
----
git push --prune https://github.com/marcelbaumann/tangly-os.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
----

==== Findings

. We needed to manually publish the public key on http://keys.gnupg.net[keys.gnupg.net]
. Gradle build file has a condition include to disable the signing plugin on the CI pipeline because keys and associated authentication are not available.
 I decided not to upload private keys to https://bitbucket.org/[bitbucket].
 See the documentation at the beginning of the Gradle build file for details.

IMPORTANT: Set the property if you want to sign the component artifacts and publish to Maven Central.

[#website-publication]
=== Website Publication

==== Configure asciidoctor

The new version of hugo support configuration of asciidoctor through config.toml therefore no manipulation of asciidoctor is needed.
As a bonus the file generated by PlantUml are created in the correct folder.
We still need to install the referenced packages.

[code]
----
sudo gem install asciidoctor-diagram
sudo gem install asciidoctor-rouge
sudo gem install asciidoctor-html5s
sudo gem install asciimath
----

==== Create Website

The tangly open source components website is hosted https://tangly-team.bitbucket.io/[here].

Read the instructions in the asciidoctor script file under the scripts folder.
Four scripts are provided to generate the Hugo static site with associated structure and theme.

. the script _initiateHugo.sh_ creates the layout of the site and retrieve the theme.
. the script _populateHugo.sh_ populates the site with our content.

Upon completion of local development you must start a local Hugo server and generate the indexing files for https://lunrjs.com/[lunr] search.
Before uploading the site stop the Hugo local server.

. the script _completeHugo.sh_ generates the static pictures and copy them to the static folder and publish the whole site on bitbucket.

Upon completion the site is published on the web for all.
