---
title: "Design Conventions"
date: 2020-05-01
weight: 60
draft: false
---

= Design Conventions
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:revnumber: v0.1
:revdate: 2020-05-31
:homepage: https://www.tangly.net/
:description: Design conventions for the open source components of tangly
:keywords: agile, architecture, design
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0
:sectnums:

== Audit Event Conventions

The _event_ field is one of of the following values

import :: any entity imported from an external source is audited
export :: any entity exported to an external source is audited
create :: each time a file is generated and exported shall be audited.
For example the creation of an invoice document is audited.
login :: login of a user
logout :: logout of a user

The _component_ field is one of the tangly component

* net.tangly.bus
* net.tangly.commons
* net.tangly.dev
* net.tangly.fsm
* net.tangly.gleam
* net.tangly.orm
* net.tangly.ports
* net.tangly.commons.ui.vaadin

== Java Conventions

=== toString Method

The method implementation uses a _String.format()_ approach.
We assume that Java will introduce intrinsics support for an efficient implementation of toString method based on _String.format()_.
As soon as the intrisics is available we will migrate to the supported version as stated in JEP 348.

The _toString_ method is used to create detailed audit and looging messages and support production error searching.
The format of the message is based on the build-in format defined in the JDK for Java records.
