/*
 * Copyright 2024 Marcel Baumann
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 *          https://apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
 * OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 *
 */

package net.tangly.core.domain;

import net.tangly.core.HasDate;
import net.tangly.core.HasName;
import net.tangly.core.HasText;
import org.jetbrains.annotations.NotNull;

import java.time.LocalDate;
import java.util.Map;

/**
 * Defines a document and its metadata stored in the system as immutable record.
 *
 * @param name      human-readable name of the document
 * @param uri       uri is relative to the domain documents root folder
 * @param date      date when the document was created
 * @param text      human-readable text describing the document
 * @param generated flag indicating if the document was generated by the ERP system. A generated document is not editable and is not subject to retention policies.
 *                  It can be regenerated at any time.
 * @param values    map of key-value pairs used to store metadata of the document
 */
public record Document(@NotNull String name, @NotNull String uri, @NotNull LocalDate date, String text, boolean generated, @NotNull Map<String, String> values)
    implements HasName, HasDate, HasText {
    static final String OWNER = "owner";
    static final String ID = "id";
    static final String MEDIA_TYPE = "mediaType";
    static final String READONLY = "readonly";
}
