---
title: "Readme"
date: 2019-05-01
weight: 10
---

= Application User Interface Demonstration
:ref-groupId: net.tangly
:ref-artifactId: ui-app

image:https://img.shields.io/badge/license-Apache%202-blue.svg[Apache License 2.0]
image:https://img.shields.io/maven-central/v/{ref-groupId}/{ref-artifactId}[Maven Central]
https://javadoc.io/doc/{ref-groupId}/{ref-artifactId}[image:https://javadoc.io/badge2/{ref-groupId}/{ref-artifactId}/javadoc.svg[javadoc]]
image:https://github.com/tangly-team/tangly-os/actions/workflows/workflows.yml/badge.svg[build]
image:https://img.shields.io/github/issues-raw/tangly-team/tangly-os[issues]
image:https://img.shields.io/github/discussions/tangly-team/tangly-os[discussions]

== How To Build and Run

The whole application can be build and executed with:

[source,bash]
----
./gradlew run
----

The application is available under http://localhost:8080[Demonstration].

=== Entities, Identifiers, Tags, Comments

The demonstration application shows the user interface for

Simple Entities:: with internal object identifier, external identifier, name, validity time range and text.
Complex Entities:: simple entities with tags and comments.
Comments View:: An entity can have a set of human-readable comments.
Tags View:: An entity can have a set of tags with optional or mandatory values.
Codes:: Enumeration values similar to reference tables are supported.
One-to-One Relation:: relation between two entities.
One-to-Many Relation:: collection between an owning entity and a set of owned entities
CRUD Operations:: are provided for simple and complex entitites.
The available operations are either for read-only entities or modifiable entities.
