---
title: "Commercial Support"
linkTitle: "Commercial Support"
weight: 60
---

tangly llc company provides commercial support for the tangly open source components.

We do product development and consulting for European companies.
Onsite coaching is limited to the German part of Switzerland.

mailto:info@tangly.net[Contact us, Commercial support] for inquiries on commercial support for tangly OS components, Modern Java, DevOps and Vaadin.

== Team

[cols="2,5,1",options="header"]
|===
^| Who
^| Capabilities
^| LinkedIn
|Marcel Baumann
|Java Developer and Architect, Agile Catalyst and Scrum Master, DevOps Engineer
|
+++
<a class="libutton" href="https://www.linkedin.com/comm/mynetwork/discovery-see-all?usecase=PEOPLE_FOLLOWS&followMember=marcelbaumann" target="_blank">Follow on LinkedIn</a>
+++
|Alexandra Junghans
|Java Developer and Architect, Agile Coach, Scrum Master and Facilitator
|
+++
</style>
<a class="libutton" href="https://www.linkedin.com/comm/mynetwork/discovery-see-all?usecase=PEOPLE_FOLLOWS&followMember=junghana" target="_blank">Follow on LinkedIn</a>
+++

|===

== Contact Information

[%noheader,frame=none,grid=none,width=75%,cols="1,4"]
|===
| *Postal Address:* | tangly llc +
Lorzenhof 27 +
6330 *Cham* +
_Switzerland_
| *Plus Code:*      | 8FVC5FM5+Q6G
| *Email:*          | mailto:info@tangly.net[email contact]
| *Phone:*          | +41 79 778 86 89
| *LinkedIn:*       | https://www.linkedin.com/company/tangly-llc/[tangly llc]
|===
