---
title: "Readme"
date: 2019-05-01
weight: 10
---

= Application User Interface Library
:ref-groupId: net.tangly
:ref-artifactId: apps

image:https://img.shields.io/badge/license-Apache%202-blue.svg[Apache License 2.0]
image:https://img.shields.io/maven-central/v/{ref-groupId}/{ref-artifactId}[Maven Central]
https://javadoc.io/doc/{ref-groupId}/{ref-artifactId}[image:https://javadoc.io/badge2/{ref-groupId}/{ref-artifactId}/javadoc.svg[javadoc]]
image:https://github.com/tangly-team/tangly-os/actions/workflows/workflows.yml/badge.svg[build]
image:https://img.shields.io/github/issues-raw/tangly-team/tangly-os[issues]
image:https://img.shields.io/github/discussions/tangly-team/tangly-os[discussions]

== Purpose

The library provides the abstractions to create a Vaadin user interface with multiple bounded domains.
The application can optionally declares ports to provide a REST interface for selected bounded domains.

== Download and Documentation

You need to add JUnit 5 dependencies before using this library.
If you are using Maven or Gradle, add the following dependency after declaring the JUnit 5 dependency.
We recommend using __assertJ__ assertion library to write more legible conditions.

The library can be included in Maven as

[source,xml]
----
    <dependency>
      <groupId>net.tangly</groupId>
      <artifactId>apps</artifactId>
      <version>0.2.7</version>
    </dependency>
----

The library can be included in Gradle as

[source,groovy]
----
    testImplementation "net.tangly:apps:0.2.7"
----

The documentation can be found under {ref-tangly-blog-url}/docs/apps/[apps documentation].

For any further questions, you can use the forum https://github.com/orgs/tangly-team/discussions[tangly-Discussions].

== Awesome Sponsors and Developers

Corporate sponsors are

* https://www.tangly.net[tangly llc]

Individual developers are

* https://www.linkedin.com/in/marcelbaumann/[Marcel Baumann]
* https://www.linkedin.com/in/junghana/[Alexandra Junghans]
