= 1. Remove usage of Google Guava Library

Date: 2018-02-20

== Status

Implemented

== Context

The JDK 8 and JDK 9 provide better replacement methods for Guava functions.

Guava is an external library of high quality but still an additional dependency in the application. We always follow the
rule to use language and standard library constructs over using external libraries.

The advantage is better integration, always synchronized with a new release of the JDK and no incompatibilities. The
drawback is sometimes a slightly more cumbersome syntax or solution.

== Decision

All Guava usages shall be replaced by JDK standard function. The main advantages are
1. Current JDK versions provide own implementation e.g. in the Objects class
2. Guava dependency is removed from our source code and compiled artifacts
3. Guava is not optimized for idioms used in current JDK such as streams and extensive use of lambdas 

== Consequences

Ontology based on tags are not hard defined through a type system. Checks have to be implemented to guaranty adequate
level of tracking.