---
title: "Contributing Guidelines"
linkTitle: "Contributing Guidelines"
weight: 1000
date: 2020-09-10
---

== Contribution Guidelines
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0

=== How to contribute to {ref-tangly} Open Source Components

This is an open source outcome.
We love getting patches and contributions to make our components and their documentation even better.

=== Contributing to tangly Open Source Components

The components live in {ref-site}.
The git repository and the issue tracker are public and accessible to all interested parties.

=== Contributor License Agreement

Source Code contributions to this outcome must be published under Apache 2.0 license.

All documentations and texts to this outcome must be published under CC-BY-SA 4.0.

This simply gives us permission to use and redistribute your contributions as part of the outcome.

=== Code reviews

All submissions, including submissions by outcome members, require review.
We use bitbucket pull requests for this purpose.
Consult bitbucket https://www.atlassian.com/git/tutorials/making-a-pull-request[Tutorial and Help] for more information on using pull requests.

=== Previewing your changes

Source Code Changes::
 Build locally code changes with the provided Gradle scripts.
Documentation Changes::
 The scripts to generate and populate the site from the outcome clone repository are located under
 https://bitbucket.org/tangly-team/tangly-os/src/master/src/main/scripts/[scripts].

=== Creating issues

Alternatively, if there’s something you’d like to see (or if you’ve found something that isn’t working the way you’d expect),
but you’re not sure how to fix it yourself, please create an issue in https://bitbucket.org/tangly-team/tangly-os/issues[Issue Tracker].

