---
title: "Contributing Guidelines"
linkTitle: "Contributing Guidelines"
weight: 1000
date: 2020-09-10
description: Contributing guidelines for the open source components of tangly OS product
---

:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]

This is an open source product.
We love getting patches and contributions to make our components, and their documentation even better.

== Contributing to tangly Open Source Components

The components live in {ref-site}.
The git repository and the issue tracker are public and accessible to all interested parties.

You can create the set of git remotes with the following instructions.

[source,console]
----
git remote add origin-github git@github.com:marcelbaumann/tangly-os.git                  // <1>
git remote add origin-gitlab git@gitlab.com:marcelbaumann/tangly-os.git                  // <2>
git remote add origin-bitbucket git@bitbucket.org:tangly-team/tangly-os.git              // <3>
git remote add origin-hslu https://gitlab.switch.ch/tangly/tangly-os.git                 // <4>

git remote -v                                                                            // <5>
git push <remote> master                                                                 // <6>
git remote rm <remote>                                                                   // <7>
----

<1> Primary git repository of the project
<2> Secondary mirrored git repository of the project
<3> Third mirrored git repository of the project exists due to historical reason
<4> Repository for the lectures at the technical university of Lucerne, Switzerland (https due to limitations of their server)
<5> List all remote defined for this git project
<6> Push the local master branch to the selected remote
<7> Remove the given remote from this git project

== Contributor License Agreement

Source Code contributions to this product must be published under Apache 2.0 license.

All documentations and texts to this product must be published under CC-BY-SA 4.0.

This simply gives us permission to use and redistribute your contributions as part of the product.

== Code reviews

All submissions, including submissions by product members, require review.
We use bitbucket pull requests for this purpose.
Consult bitbucket https://www.atlassian.com/git/tutorials/making-a-pull-request[Tutorial and Help] for more information on using pull requests.

== Previewing your changes

Source Code Changes::
 Locally build the code changes with the provided Gradle scripts.
Documentation Changes::
 The scripts to generate and populate the site from the product clone repository are located under
 https://bitbucket.org/tangly-team/tangly-os/src/master/src/main/scripts/[scripts].

== Creating issues

Alternatively, if there’s something you’d like to see (or if you’ve found something that is not working the way you would expect).
You are not sure how to fix it yourself, please create an issue in https://bitbucket.org/tangly-team/tangly-os/issues[Issue Tracker].

