---
title: "Building Block View"
date: 2019-05-01
weight: 50
---

:ref-javalin: https://javalin.io/[Javalin]

ifndef::imagesdir[:imagesdir: ./pics]

[[section-building-block-view]]
== Building Block View

=== Bounded Domain as a Building Block

=== Bounded Domain User Interface

=== Bounded Domain Persistence

=== Bounded Domain Export and Import

=== Rest Services for a Bounded Domain

A bounded domain is the building block for a modular monolith architecture approach.
Each bounded domain is a self-contained module that encapsulates the business logic and data for a specific domain.

A bounded domain can provide a REST interface to expose its functionality to other modules or external clients.
The definition and documentation of the REST services are part of the bounded domain and should be packaged with the domain artifacts.

THe REST services are documented using the OpenAPI specification and the documentation is displayed using Swagger UI.

[NOTE]
====
We have one REST services specification per bounded domain.
The Swagger UI shall be used to publish the REST services for all bounded domains part of the modular monolith application.

The application uses the {ref-javalin} framework to implement the REST services.
OpenAPI and Swagger plugins are used to document and publish the documentation of the REST services.
====
