---
title: "Readme"
date: 2019-05-01
weight: 10
---

= Development Libraries
:ref-groupId: net.tangly
:ref-artifactId: dev

include::../src/main/fragments/_badges.adoc[]

== Purpose

== Download and Documentation

The library can be included in Maven as

[source,xml]
----
    <dependency>
      <groupId>net.tangly</groupId>
      <artifactId>dev</artifactId>
      <version>0.2.7</version>
    </dependency>

----

The library can be included in Gradle as

[source,groovy]
----
    implementation "net.tangly:dev:0.2.7"
----

The documentation can be found under {ref-tangly-doc-url}/dev/[Commons documentation]

For any further questions, you can use the forum https://github.com/orgs/tangly-team/discussions[tangly-Discussions].

== Contribution

You are welcome to contribute to the product with pull requests on Bitbucket.You can download the source files from the
https://bitbucket.org/tangly-team/tangly-os.git[bitbucket git repository] and build the library with the provided gradle configuration file.

If you find a bug or want to request a feature, please use the https://bitbucket.org/tangly-team/tangly-os/issues[issue tracker].

== License

The source code is licensed under https://www.apache.org/licenses/LICENSE-2.0[Apache license 2.0].

The documentation and examples are licensed under https://creativecommons.org/licenses/by/4.0/[Creative Common (CC Attribution 4.0 International)].

== Awesome Sponsors and Developers

Corporate sponsors are

* https://www.tangly.net[tangly llc]

Individual developers are

* https://linkedin.com/in/marcelbaumann[Marcel Baumann]
