---
title: "Readme"
date: 2019-05-01
weight: 10
---

= ERP Collaborators Component
:ref-groupId: net.tangly.erp
:ref-artifactId: collaborators

image:https://img.shields.io/badge/license-Apache%202-blue.svg[Apache License 2.0]
image:https://img.shields.io/maven-central/v/{ref-groupId}/{ref-artifactId}[Maven Central]
https://javadoc.io/doc/{ref-groupId}/{ref-artifactId}[image:https://javadoc.io/badge2/{ref-groupId}/{ref-artifactId}/javadoc.svg[javadoc]]
image:https://github.com/tangly-team/tangly-os/actions/workflows/workflows.yml/badge.svg[build]
image:https://img.shields.io/github/issues-raw/tangly-team/tangly-os[issues]
image:https://img.shields.io/github/discussions/tangly-team/tangly-os[discussions]

== Purpose

The *tangly erp collaborators* bounded domain component provides regular business model abstractions for business applications written in Java. The component
is using records and requires *{ref-java-current-version} or higher*.

*Try it out*.

== Download and Documentation

The library can be included in Maven as

[source,xml]
----

<dependency>
    <groupId>net.tangly.erp</groupId>
    <artifactId>collaborators</artifactId>
    <version>0.2.8</version>
</dependency>

----

The library can be included in Gradle as

[source,groovy]
----
    implementation "net.tangly.erp:collaborators:0.2.8"
----

The documentation can be found under {-url}/domains/collaborators/[Business documentation].

For any further questions, you can use the forum https://github.com/orgs/tangly-team/discussions[tangly-Discussions].

== Contribution

You are welcome to contribute to the product with pull requests on Bitbucket.You can download the source files from the
https://bitbucket.org/tangly-team/tangly-os.git[bitbucket git repository] and build the library with the provided gradle configuration file.

If you find a bug or want to request a feature, please use the https://bitbucket.org/tangly-team/tangly-os/issues[issue tracker].

== License

The source code is licensed under https://www.apache.org/licenses/LICENSE-2.0[Apache license 2.0].

The documentation and examples are licensed under https://creativecommons.org/licenses/by/4.0/[Creative Common (CC Attribution 4.0 International)].

== Awesome Sponsors and Developers

Corporate sponsors are

* https://www.tangly.net[tangly llc]

Individual developers are

* https://www.linkedin.com/in/marcelbaumann[Marcel Baumann]
