---
title: "Bounded Domain Models"
date: 2019-05-01
weight: 50
---
== Bounded Domains Models

=== Codes Model

The abstraction of a reference table or reference codes.
A code table is an extensible set of values.
You can add values when needed and extend the model with temporal activation if desired.
For example, currencies are typical code values with a temporal duration; well-known retired currencies are the European Currency Unit _ECU_ or the German deutsche mark _DM_.
New values can be added without recompiling the application.
A code can have an optional validity period or simply a flag stating it is active or not.
To guaranty consistency with exported datasets, a code format shall never be deleted, only be disabled.
Code instances are immutable objects.

[NOTE]
====
You can smooth your transition from enumeration types to reference codes.
Extend your enumeration types with the _Code_ interface.

Now you can transform your code to support generic reference codes and make your application more dynamic to domain model changes.
====

[plantuml,bus-codes-uml,svg]
....
@startuml

interface Code {
    int id()
    String code()
    boolean isEnabled()
}

class CodeType <T extends Code> {
    Class<T> clazz()
    List<T> codes()
    List<T> activeCodes()
    List<T> inactiveCodes()
    Optional<T> findCode(int id)
    Optional<T> findCode(String code)
}

class CodeImp {}

CodeImp <|-- Code

@enduml
....

=== Core Model

==== Entity

An entity and all subclasses have a set of attributes present in any CSV file.

oid::
object identifier of the entity instance as the string representation of a 64 bits long.
The value is mandatory.
id::
identifier of the entity instance as a string.
The value is optional.
name::
human-readable name of the entity instance as a string.
The value is optional.
text::
human-readable description of the entity instance as a long string.
The value is optional.
fromDate::
start date when the entity instance is active.
The value is optional.
toDate::
end date when the entity instance is active.
Upon the end date, the entity should be read-only and no more edited in the system.
The value is optional.

[plantuml,bus-core-uml,svg]
....
@startuml

interface HasId {
    String id()
    String name()
}

interface HasOid {
    long oid()
}

interface HasTags {}

interface HasComments {}

interface HasOwner {}

HasOid <|.. HasOwner

interface Entity {
    + String text()
    + LocalDate fromDate()
    + LocalDate toDate()
}

HasOid <|.. Entity
HasId <|.. Entity
HasTags <|.. Entity
HasComments <|.. Entity

abstract class EntityImp {}

EntityImp *-- Tag : tags
EntityImp *-- Comment : comments

Entity <|.. EntityImp

class Address << (R,orchid) >>

class Tag <<record>>

class Comment {}

Comment *-- Tag : tags

class EmailAddress << (R,orchid) >>

@enduml
....

See our blogs for a discussion concerning the cornerstone abstractions of the business core model:

* link:../../../blog/2020/entities-identifiers-external-identifiers-and-names[Entities, internal Identifiers, external Identifiers, and Names],
* link:../../../blog/2020/the-power-of-tags-and-comments[The Power of Tags and Comments],
* link:../../../blog/2020/reference-codes[Reference Codes].

== Customer Relationship Model CRM

[plantuml,bus-crmRealm-uml,svg]
....
@startuml

package Shared <<Rectangle>> {
    interface HasId {
        String id()
        String name()
    }

    interface HasOid {
        long oid()
    }

    interface HasTags {}

    interface HasComments {}

    interface HasOwner {
    }
    HasOid <|.. HasOwner

    interface Entity {
        + String text()
        + LocalDate fromDate()
        + LocalDate toDate()
    }
    HasOid <|.. Entity
    HasId <|.. Entity
    HasTags <|.. Entity
    HasComments <|.. Entity

    abstract class EntityImp {
    }
    EntityImp *-- Tag : tags
    EntityImp *-- Comment : comments
    Entity <|.. EntityImp

    class Tag <<record>>

    class Comment {
    }
    Comment *-- Tag : tags

    class BankConnection <<(R,orchid) record>> {
        String iban
        String bic
        String institute
    }

    class Address <<(R, orchid) record>> {
        String street
        String extended
        String poBox
        String postcode
        String locality
        String region
        String country
    }

    class EmailAddress <<(R, orchid) record>> {
        String domain
        String recipient
    }

    class PhoneNr <<(R, orchid) record>> {
        String number
    }
}

package Bounded_Domain_CRM <<Rectangle>> {

    interface Entity {}

    class CrmEntity implements Entity {}

    HasTags <|.. CrmEntity

    class LegalEntity implements CrmEntity {}

    CrmEntity <|.. LegalEntity

    class NaturalEntity {}

    CrmEntity <|.. NaturalEntity

    class Employee implements CrmEntity {}

    Employee o-- NaturalEntity
    Employee o-- LegalEntity

    enum ActivityCode {
    }
    Code <|-- ActivityCode

    class Activity {
    }
    Activity *-- ActivityCode : code

    class Contract {
    }
    Contract o-- LegalEntity : seller
    Contract o-- LegalEntity : sellee

    enum InteractionCode {
    }
    Code <|-- InteractionCode

    class Interaction {
    }
    Interaction *-- InteractionCode : code
    Interaction *-- Activity : activities

}

package Bounded_Domain_Invoices <<Rectangle>> {
    interface InvoiceLine {
    }

    class InvoiceItem <<(R,orchid) record>> {
        int position
        String text
        BigDecimal quantity
    }
    InvoiceLine <|-- InvoiceItem
    InvoiceItem o-- Article : article


    class Subtotal <<(R,orchid) record>> {
        int position
        String text
    }
    InvoiceLine <|-- Subtotal
    Subtotal o-- InvoiceItem : items

    class Invoice {
    }
    Invoice o-- LegalEntity : seller
    Invoice o-- LegalEntity : sellee
    Invoice *-- InvoiceLine : items

    enum ProductCode {
    }
    Code <|-- ProductCode

    class Article <<(R, orchid) record>> {
        String id
        String name
        String text
        BigDecimal unitPrice
        String unit
        BigDecimal vatRate
    }
    Article o-- ProductCode : code
}

package Bounded_Domain_Products <<Rectangle>> {

    class Product {
    }

    class Assignment {
    }

    class Effort {
    }
}

package Bounded_Domain_Ledger <<Rectangle>> {
    class AccountEntry {
    }

    class Account {
    }
    Account *-- AccountEntry : entries
    Account *-- Account : aggregatedAccounts

    class Transaction {
    }
    Transaction o-- AccountEntry : debit
    Transaction o-- AccountEntry : credit

    class Ledger {
    }
    Ledger *-- Account : accounts
    Ledger *-- Transaction : journal
}

@enduml
....

== Invoices Model

=== Concepts

Invoices define a business bounded domain as defined in domain-driven design approach.
They are not constrained through external entities such as products, contracts or legal entities.
External entities can provide hints to streamline the creation of regular invoices.
The invoice article identifier is available as an external identifier to the article bounded domain.
Similar identifiers are available for legal entities.

VAT rates are defined within an article definition.
Therefore, different VAT rates require different article definitions.
For example, in Switzerland, a service company has two VAT rates.
One for regular services and one for services exempted from VAT taxes.

The currency is defined at the invoice level, meaning all invoice items and subtotals should use the same currency.

=== Archiving

An invoice contains all the information to create a legally binding document and hove no dependencies to external systems.
Invoices should have a unique identifier for accounting purposes.
A good practice is to use the identifier as part of the archived file to streamline traceability.
Invoices can be stored in a database, exported as a PDF file or as a JSON file.
The PDF file is human-readable and adequate for document archiving and legal auditing.
The JSON file is an adequate archive format which can digitally be processed.

[plantuml,bus-invoice-uml,svg]
....
@startuml

package net.tangly.bus.crmRealm {
    class LegalEntity {}

    class BankConnection << (R,orchid) >> {
        String iban
        String bic
        String institute
    }

    class Contract {}
}

package net.tangly.bus.invoices {
class Product << (R,orchid) >> {
    String productId
    String description
    BigDecimal unitPrice
    String unit
    BigDecimal vatRate
}

class Invoice {
    String id
    String contractId
    LocalDate deliveryDate
    LocalDate invoicedDate
    LocalDate dueDate
    Currency currency
    String text
    String paymentConditions
}

note right: contractId is the identifier for the contract instance in the CRM package.

Invoice *-- InvoiceLine : lines
Invoice o--> LegalEntity : invoicingEntity
Invoice o--> LegalEntity : invoicedEntity
Invoice *--> BankConnection : invoicingConnection

interface InvoiceLine {}

class InvoiceItem << (R,orchid) >> {}

InvoiceLine <|.. InvoiceItem

InvoiceItem o-- Product : article

class Subtotal << (R,orchid) >> {}

InvoiceLine <|.. Subtotal
Subtotal o-- InvoiceLine

}

@enduml
....

=== Ledger Model

[plantuml,bus-ledger-uml,svg]
....
@startuml

class AccountEntry {}

class Transaction {}

class Account {}

class Ledger {}

Ledger *-- Account : accounts
Ledger *-- Transaction : transactions

@enduml
....

=== Products Model

[plantuml,bus-article-uml,svg]
....
@startuml

class Assignment {}

class Effort {}

class Project {}

@enduml
....

