---
title: "Core Models"
date: 2019-05-01
weight: 50
---
== Core Models

=== Codes Model

The abstraction of a reference table or reference codes.
A code table is an extensible set of values.
You can add values when needed and extend the model with temporal activation if desired.
For example, currencies are typical code values with a temporal duration; well-known retired currencies are the European Currency Unit _ECU_ or the German deutsche mark _DM_.
New values can be added without recompiling the application.
A code can have an optional validity period or simply a flag stating it is active or not.
To guaranty consistency with exported datasets, a code format shall never be deleted, only be disabled.
Code instances are immutable objects.

[NOTE]
====
You can smooth your transition from enumeration types to reference codes.
Extend your enumeration types with the _Code_ interface.

Now you can transform your code to support generic reference codes and make your application more dynamic to domain model changes.
====

[plantuml,bus-codes-uml,svg]
....
@startuml

interface Code {
    int id()
    String code()
    boolean isEnabled()
}

class CodeType <T extends Code> {
    Class<T> clazz()
    List<T> codes()
    List<T> activeCodes()
    List<T> inactiveCodes()
    Optional<T> findCode(int id)
    Optional<T> findCode(String code)
}

class CodeImp {}

CodeImp <|-- Code

@enduml
....

=== Core Model

==== Entity

An entity and all subclasses have a set of attributes present in any CSV file.

oid::
Object identifier of the entity instance as the string representation of a 64 bits long.
The value is mandatory.
id::
Identifier of the entity instance as a string.
The value is optional.
name::
Human-readable name of the entity instance as a string.
The value is optional.
text::
Human-readable description of the entity instance as a long string.
The value is optional.
fromDate::
Start date when the entity instance is active.
The value is optional.
toDate::
End date when the entity instance is active.
Upon the end date, the entity should be read-only and no more edited in the system.
The value is optional.

[plantuml,bus-core-uml,svg]
....
@startuml

interface HasId {
    String id()
    String name()
}

interface HasOid {
    long oid()
}

interface HasName {
}

class DateRange << (R,orchid) >> {}

interface HasDateRange {}

class Tag {}
class TagType{}

interface HasTags {}

class Comment {}

interface Code {}

class TypeRegistry {}

interface HasComments {}

interface Entity {
    + String text()
    + LocalDate fromDate()
    + LocalDate toDate()
}

HasOid <|-- Entity
HasId <|-- Entity
HasName <|-- Entity
HasDateRange <|-- Entity

interface EntityExtended {}
Entity <|-- EntityExtended
HasTags <|-- EntityExtended
HasComments <|-- EntityExtended

abstract class EntityExtendedImp {}

EntityExtended <|-- EntityExtendedImp
EntityExtendedImp *-- Tag : tags
EntityExtendedImp *-- Comment : comments

class Address << (R,orchid) >>

class Tag << (R,orchid) >>

class Comment {}

Comment *-- Tag : tags

class EmailAddress << (R,orchid) >>

@enduml
....

See our blogs for a discussion concerning the cornerstone abstractions of the business core model:

* link:../../../blog/2020/entities-identifiers-external-identifiers-and-names[Entities, internal Identifiers, external Identifiers, and Names],
* link:../../../blog/2020/the-power-of-tags-and-comments[The Power of Tags and Comments],
* link:../../../blog/2020/reference-codes[Reference Codes].

== Customer Relationship Model CRM

[plantuml,bus-crmRealm-uml,svg]
....
@startuml

package Shared <<Rectangle>> {
    interface HasId {
        String id()
        String name()
    }

    interface HasOid {
        long oid()
    }

    interface HasTags {}

    interface HasComments {}

    interface HasOwner {
    }
    HasOid <|.. HasOwner

    interface Entity {
        + String text()
        + LocalDate fromDate()
        + LocalDate toDate()
    }
    HasOid <|.. Entity
    HasId <|.. Entity
    HasTags <|.. Entity
    HasComments <|.. Entity

    abstract class EntityImp {
    }
    EntityImp *-- Tag : tags
    EntityImp *-- Comment : comments
    Entity <|.. EntityImp

    class Tag <<record>>

    class Comment {
    }
    Comment *-- Tag : tags

    class BankConnection <<(R,orchid) record>> {
        String iban
        String bic
        String institute
    }

    class Address <<(R, orchid) record>> {
        String street
        String extended
        String poBox
        String postcode
        String locality
        String region
        String country
    }

    class EmailAddress <<(R, orchid) record>> {
        String domain
        String recipient
    }

    class PhoneNr <<(R, orchid) record>> {
        String number
    }
}

package Bounded_Domain_CRM <<Rectangle>> {

    interface Entity {}

    class CrmEntity implements Entity {}

    HasTags <|.. CrmEntity

    class LegalEntity implements CrmEntity {}

    CrmEntity <|.. LegalEntity

    class NaturalEntity {}

    CrmEntity <|.. NaturalEntity

    class Employee implements CrmEntity {}

    Employee o-- NaturalEntity
    Employee o-- LegalEntity

    enum ActivityCode {
    }
    Code <|-- ActivityCode

    class Activity {
    }
    Activity *-- ActivityCode : code

    class Contract {
    }
    Contract o-- LegalEntity : seller
    Contract o-- LegalEntity : sellee

    enum InteractionCode {
    }
    Code <|-- InteractionCode

    class Interaction {
    }
    Interaction *-- InteractionCode : code
    Interaction *-- Activity : activities

}

@enduml
....

