---
title: "ERP Ports"
date: 2020-06-01
weight: 50
draft: false
---
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:revnumber: v0.1
:revdate: 2020-05-31
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0

== CRM Ports

The CRM ports provide a bidirectional interface to persistent file storage.

CRM entities can be stored to and retrieved from tab separated values _TSV_ files.

== Invoices Ports

Invoices are stored to and retrieved from JSON files.

== Ledger Ports

_To be written_

=== Ledger Banana Import Handler

==== Importing Ledger Structure

The following steps export the information from the banana application:

* Select the accounts tab displaying all the accounts and their structure of the period
* Goto Data > Export Rows > Export Rows to txt
* Select the destination file
* If necessary change the extension to _tsv_

The generated file is a CSV file containing the whole ledger account plan. The separator is TAB.

==== Importing Transactions

The following steps export the information from the banana application:

* Select the transaction tab displaying all the transactions of the period
* Goto Data > Export Rows > Export Rows to txt
* Select the destination file
* If necessary change the extension to _tsv_

The generated file is a CSV file containing the transaction details. The separator is TAB.
It is a good practice to generate a file per fiscal year.

All imported transactions should use the same ledger structure to support benchmarking and reporting over multiple periods.
