= Build Process

== Purpose

The definition of plugins to configure a multimodule Gradle project uses the current good practices for a Gradle project.

We use the newer central configuration feature for all plugins and libraries used in the project.
The configuration file is `libs.versions.toml`.

== Convention Plugins

Java Common Conventions::
Configuration and dependencies used in all Java modules

[NOTE]
====
The other plugins could be eliminated by using the Java Common Conventions plugin and streamlining the project setup.
====

== Commands

The set of Gradle command line special commands we seldom use:

* To publish all modules in local maven repository `./gradlew publishMavenJavaPublicationToMavenLocal`
* To publish all modules in maven central repository `./gradlew publishMavenJavaPublicationToMavenRepository`
* To generate static and aggregate code coverage metrics `./gradlew test testCodeCoverageReport testAggregateTestReport`
* To detect newer versions of libraries `./gradlew dependencyUpdates -Drevision=release`
* To update sonar cloud `./gradlew sonarqube -Dsonar.login=<login token>`
* To run all tests locally as sanity check `./gradlew clean build test javadoc -Pvaadin.productionMode`
* To create a production release `./gradlew net.tangly.erp.ui:installDist -Pvaadin.productionMode`
* To detect vulnerabilities `./gradlew ossIndexAudit --info`
* To check licenses of dependencies `./gradlew checkLicense`

Run these commands from the root folder of the project.

A good sanity check is to run the following command before pushing the code to the repository:

`./gradlew clean build test javadoc testCodeCoverageReport testAggregateTestReport -Pvaadin.productionMode`

== Tips

To update the zsh profile commands you shall run `source ~/.zshrc`.



The build process of the Gradle build file requires these variables to run without errors.
