---
title: "FSM-002: Publish Maven Central Artifacts"
linkTitle: "Publish Maven Central Artifacts"
date: 2020-01-01
weight: 202
---

== FSM-002 Publish Artifacts on Public Java Components Repository

Date: 2020-01-01

=== Status

Retired

=== Links

Superseded by: link:../os-005-publish-maven-central-artifact/[OS-0005]

=== Context

The library is mature enough to be used in commercial and academic projects.
The library was used in internal projects and refined to fulfill these requirements.
More customers will validate the usefulness of the library and identify extensions for further releases.

=== Decision

The library shall be published on maven central and be accessible to a wide range of developers and organizations.
A website shall be set up to provide adequate documentation for users.

The {ref-tangly-blog-url}/docs/fsm/[FSM website] will use a static web approach to minimize costs and provide good legibility.

The library will be published on {ref-maven-central} to maximize potential usage.

The ADR FSM-001 supports this evolution.

=== Consequences

* We have to establish a publishing process at the company level to deploy signed artifacts to maven central repository.
* We have to establish a public website to host the documentation of public published libraries.
* We have to support semantic versioning of all future published releases.
