---
title: "Release Notes"
date: 2019-05-01
weight: 20
---
:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0


== FSM Library Change Logs

This document provides a high-level view of the changes introduced in the FSM library by release.
For a detailed view of what has changed, refer to the https://bitbucket.org/tangly-team/tangly-os[repository] git commits.

=== 0.2.7 (2023-10-31)

* Update of library dependencies, update to JDK-20, and modern Gradle approach to build solutions.
* Added statechart diagram support for _smcat_ and _mermaid_ formats.
* Actor library now uses the standard API FLow implementation and virtual thread executor.

=== 0.2.6 (2021-04-30)

* Update of the dependencies
* Corrected bug in the declaration of local transitions through the builder mechanism

=== 0.2.5 (2020-08-31)

* Update of the dependencies

=== 0.2.4 (2020-06-30)

* FSM library is now a regular Java 9 module (thanks to the new module support in Gradle 6.4)
* The new Java record construct is used to simplify the API of the library
* The library requires JDK 14 and all dependencies were updated to the current version

=== 0.2.3 (2020-03-06)

* Dependencies were updated to current versions
* Unit test examples and documentation improvements

=== 0.2.2 (2019-05-17)

* Unit tests were extended to provide better code coverage
* Typos in the https://blog.tangly.net/[static site documentation] were corrected

=== 0.2.1 (2019-05-16)

* Initial release of the library
