#!/bin/bash
/usr/local/Cellar/asciidoctor/2.0.9/bin/asciidoctor_brew -r asciidoctor-diagram -r pygments "$@"

# must retrieve the used gem for asciidoctor
# sudo gem install asciidoctor-diagram.rb
# sudo gem install pygments.rb

# change asciidoctor to load the gem into asciidoctor when called from ruby
# mv asciidoctor asciidoctor_brw
# chmod +x asciidoctor