=== Maven Central Publication

. Publish artifacts of component with __gradle publishAllPublicationsToMavenRepository__
.. Pre activity on bitbucket to check the project compile through the continuous integration pipeline
.. Post activity on git to tag the published package. The tag is of the form __AcronymComponent-MajorVerion-MinorVersion-PatchVersion__ as
 ``git tag label`` and ``git push origin --tags``
. Log into https://oss.sonatype.org/#welcome[Sonatype Maven Central Repository]
.. Go to https://oss.sonatype.org/#stagingRepositories[Staging Repositories]
.. Find your temporary repository at the end of list
.. Review the content of the repository
.. Close the repository __button on tool list__
.. Close stage is initiated and checks are performed. If everything was fine the content is published
.. Release the artifact __button on tool list__

==== Findings
. We needed to manually publish the public key on http://keys.gnupg.net[keys.gnupg.net]
. Gradle build file has a condition include to disable the signing plugin on the CI pipeline because keys and associated authentication are not
available. See the documentation at the beginning of the Gradle build file for details.

IMPORTANT: Set the property if you want to sign the component artifacts and publish to Maven Central

=== Web Site Publication

. Update Hugo pipeline to run planUML with asciidoctor. Read the instructions in the asciidoctor script file under the scripts folder.
. Two scripts are provided to generate the Hugo static site with associated structure and theme.
.. the script __initiateHugo.sh__ creates and populates the site. Upon completion you can start a local Hugo server and look at the site if desired.
.. the script __completeHugo.sh__ generates the static pictures and copy them to the static folder and publish the whole site on bitbucket. Upon
completion the site is published on the web for all.
