=== Maven Central Publication

. Publish artifacts of component with __gradle publishAllPublicationsToMavenRepository__
. Log into [Sonatype Maven Central Repository]()https://oss.sonatype.org/#welcome)
.. Go to [Staging Repositories](https://oss.sonatype.org/#stagingRepositories)
.. Find your temporary repository at the end of list
.. Review the content of the repository
.. Close the repository __button on tool list__
.. Close stage is initiated and checks are performed. If everything was fine the content is published
.. Release the artifact __button on tool list__

==== Findings
. We needed to manually publish the public key on []keys.gnupg.net](http://keys.gnupg.net)

=== Web Site Publication

. Update Hugo pipeline to run planUML with asciidoctor. Read the instructions in the asciidoctor script file under the scripts folder.
. Two scripts are provided to generate the Hugo static site with associated structure and theme.
.. the script __initiateHugo.sh__ creates and populates the site. Upon completion you can start a local Hugo server and look at the site if desired.
.. the script __completeHugo.sh__ generates the static pictures and copy them to the static folder and publish the whole site on bitbucket. Upon
completion the site is published on the web for all.
