:company: https://www.tangly.net/[tangly llc]
:copyright: CC-BY-SA 4.0
:icons: font
:source-highlighter: pygments
:pygments-style: manni

== Maven Central Publication

. Publish artifacts of component with ``gradle publishAllPublicationsToMavenRepository -Pmode=prod``
.. Pre activitiy: test publishing with ``gradle publishToMavenLocal``
.. Pre activity: check on bitbucket the project compile through the *CI* continuous integration pipeline
.. Post activity: *tag repository* on git to identify version of the published packages.
The tag is of the form -{AcronymComponent}-MajorVersion-MinorVersion-PatchVersion- as
``git tag label`` and ``git push origin --tags``
. Log into https://oss.sonatype.org/#welcome[Sonatype Maven Central Repository]
.. Go to https://oss.sonatype.org/#stagingRepositories[Staging Repositories]
.. Find your temporary repository at the end of list
.. Review the content of the repository
.. Close the repository -button on tool list-
.. Close stage is initiated and checks are performed.
If everything was fine the content is published
.. Release the artifact -button on tool list-
. See <<website-publication>> to update the website

[CAUTION]
====
It takes up to one day until the component is visible in Maven Central website upon publication.
====

The acronyms are (the current composite acronym is TANGLY_OS meaning all components are released)

* *BDD* behavior driven development library
* *BUS* business components library
* *COMMONS* commons library
* *DEV* development tools library
* *FSM* hierarchical finite state machine library
* *GLEAM* declarative model transformation frameworks library
* *PORTS* ports library
* *UI* Vaadin user interface library

[plantuml,tangly-componentsDependencies,svg]
....
package net.tangly.bdd {}

package net.tangly.bus {}

package net.tangly.commons {
}
net.tangly.commons --> net.tangly.bus

package net.tangly.fsm {
}

package net.tangly.ports {}
net.tangly.ports --> net.tangly.commons
net.tangly.ports --> net.tangly.bus
....

=== Decisions

The open source components are stored in a mono repository.
We use de facto standard Git.
Currently we are hosted at https://bitbucket.org[bibucket].

The bitbucket repository is regularly synchronized with a github mirror repository https://github.com/marcelbaumann/tangly-os.git[github]
.
git push --prune https://github.com/marcelbaumann/tangly-os.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*


=== Findings

. We needed to manually publish the public key on http://keys.gnupg.net[keys.gnupg.net]
. Gradle build file has a condition include to disable the signing plugin on the CI pipeline because keys and associated authentication are not available.
See the documentation at the beginning of the Gradle build file for details.

IMPORTANT: Set the property if you want to sign the component artifacts and publish to Maven Central.

[#website-publication]
== Website Publication

The tangly open source components website is hosted https://tangly-team.bitbucket.io/[here].

. Update Hugo pipeline to run planUML with asciidoctor.
Read the instructions in the asciidoctor script file under the scripts folder.
. Four scripts are provided to generate the Hugo static site with associated structure and theme.
.. the script _initiateHugo.sh_ creates.
.. the script _populateHugo.sh_ populates the site.
.. the script _populateHugoImages.sh_ copies generated images at the expected location for hugo to service them.
Upon completion you can start a local Hugo server and look at the site if desired.
.. the script _completeHugo.sh_ generates the static pictures and copy them to the static folder and publish the whole site on bitbucket.
Upon completion the site is published on the web for all.

The support of -asciidoc- files and the _asciidoctor_ generator in Hugo is suboptimal.
We had to create a specific -asciidoc- shell script to mitigate the problems.
The shell script provides support for the loadable modules:

* asciidoc-diagram --to draw plantuml diagrams--
* pygments --to display legible source code--