== Docsy Theme for Hugo

The _docsy_ theme was customized to support specific needs of the tangly OS documentation static website.

=== Tips

Each section has a configuration in the front matter in the index file. The type of the section is specified to allow Hugo to retrieve the corresponding templates.

Use https://linkchecker.github.io/linkchecker/[Link Checker] to validate all links on the web site.

How to kill the hugo process hanging in a port:

[source, bash]
----
 kill -9 $(lsof -t -i:1313)
----

=== Customisation

==== Header and Footer

The header template was adapted to support AsciiMath typesetting in the browser.

The footer template was adapted to support the specific needs of the tangly OS documentation static website.
The open source copyright of our site is not well displayed in the standard footer template.

* layouts/partials/header.html
* layouts/partials/footer.html

==== Attachments

For the attachment feature we added:

* assets/scss/shortcodes.scss
* assets/scss/main.scss _added import of the shortcodes.scss styling.
* layouts/shortcodes/attachments.html

==== Comments

For the comment feature we added:

* layouts/blog/content.html _added utterances code for comments_
* layouts/partials/comments-utterances.html _partial for comment template_

==== Asciidoc Stylesheet

Exploration was started to improve the styling of https://asciidoc.org[asciidoc] documents:

* assets/scss/_asciidoctor.scss _used to better style asciidoc documents_.
* assets/scss/_shortcodes_.scss _used by the attachment extension_.
* assets/scss/_styles_projects.scss _regular extension hook for Hugo Docsy template_.
