name: Java CI

on:
    push:
        branches:
            - 'master'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: 'gradle'
            -   run: |
                    ./gradlew classes testClasses test javadoc jar
                    ./gradlew build net.tangly.erp.ui:installDist '-Pvaadin.productionMode' --no-daemon
            -   uses: actions/upload-artifact@v3
                with:
                    name: distributions
                    path: net.tangly.erp.ui/build/distributions/*.zip
                    if-no-files-found: warn
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   uses: docker/setup-buildx-action@v3
            -   uses: docker/login-action@v3
                with:
                    username: ${{secrets.DOCKER_HUB_USERNAME}}
                    password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
            -   uses: docker/build-push-action@v5
                with:
                    context: "{{defaultContext}}:net.tangly.erp.ui"
                    push: true
                    tags: ${{secrets.DOCKER_HUB_USERNAME}}/tangly-erp:latest
