name: Java CI

on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1
        - name: 'Set up Java'
          uses: oracle-actions/setup-java@v1
          with:
            website: oracle.com
            release: 18
        - name: Cache Gradle packages
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: gradle-${{ hashFiles('**/*.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties', 'gradle.properties') }}
        - name: Cache pnpm packages
          uses: actions/cache@v2
          with:
            path: |
              ~/.vaadin
              ~/.pnpm-store
            key: pnpm-${{ hashFiles('**/pnpm-lock.yaml', '**/package.json') }}
        - name: Build with Gradle
          run: ./gradlew net.tangly.erp.ui:installDist '-Pvaadin.productionMode' --no-daemon
        - name: Archive production artifacts
          uses: actions/upload-artifact@v3
          with:
            name: distributions
            path: net.tangly.erp.ui/build/distributions/*.zip
            if-no-files-found: warn
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Set up Docker Build
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./net.tangly.erp.ui/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tangly-erp:latest
