name: Java CI

on:
    push:
        branches:
            - 'master'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Restore gradle.properties
              env:
                GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
              shell: bash
              run: |
                mkdir -p ~/.gradle/
                echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
                echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '22'
                    cache: 'gradle'
            -   uses: arduino/setup-protoc@v3
            - run: |
                    ./gradlew build test javadoc -Pvaadin.productionMode=true
            -   uses: actions/upload-artifact@v4
                with:
                    name: distributions
                    path: net.tangly.erp.ui/build/distributions/*.zip
                    if-no-files-found: warn
#    deploy:
#        runs-on: ubuntu-latest
#        steps:
#            -   uses: docker/setup-buildx-action@v3
#            -   uses: docker/login-action@v3
#                with:
#                    username: ${{secrets.DOCKER_HUB_USERNAME}}
#                    password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
#            -   uses: docker/build-push-action@v5
#                with:
#                    context: "{{defaultContext}}:net.tangly.erp.ui"
#                    push: true
#                    tags: ${{secrets.DOCKER_HUB_USERNAME}}/tangly-erp:latest
