name: Java CI

on:
    push:
        branches:
            - 'master'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: 'gradle'
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '22'
                    cache: 'gradle'
            -   uses: arduino/setup-protoc@v3
            -   run: |
                    ./gradlew build
            #       ./gradlew build -Pvaadin.productionMode=true (not working with a circular dependency error)
            -   uses: actions/upload-artifact@v4
                with:
                    name: distributions
                    path: net.tangly.erp.ui/build/distributions/*.zip
                    if-no-files-found: warn
#    deploy:
#        runs-on: ubuntu-latest
#
#        steps:
#            -   uses: docker/setup-buildx-action@v3
#            -   uses: docker/login-action@v3
#                with:
#                    username: ${{secrets.DOCKER_HUB_USERNAME}}
#                    password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
#            -   uses: docker/build-push-action@v5
#                with:
#                    context: "{{defaultContext}}:net.tangly.erp.ui"
#                    push: true
#                    tags: ${{secrets.DOCKER_HUB_USERNAME}}/tangly-erp:latest
