name: Java CI

on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: 'Set up Java'
          uses: oracle-actions/setup-java@v1
          with:
              website: oracle.com
              release: 18
        - name: Set up NodeJS and npm
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'npm'
        - name: Build artifacts
          run: |
            ./gradlew build
            ./gradlew net.tangly.erp.ui:installDist net.tangly.erp.ui:installShadowDist -Pvaadin.productionMode
        - name: Archive production artifacts
          uses: actions/upload-artifact@v3
          with:
            name: distributions
            path: net.tangly.erp.ui/build/distributions/*.zip
            if-no-files-found: warn
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Set up Docker Build
          uses: docker/setup-buildx-action@v1
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./net.tangly.erp.ui/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tangly-erp:latest
