---
title: "OS 002: Publish Maven Central Artifacts"
linkTitle: "Publish Maven Central Artifacts"
date: 2020-01-01
weight: 2
---
:author: Marcel Baumann
:email: <marcel.baumann@tangly.net>
:homepage: https://www.tangly.net/
:company: https://www.tangly.net/[tangly llc]

== OS-00t Publish Artifacts on Public Java Components Repository

Date: 2020-01-01

=== Status

Superseeded by: OS-0005

=== Context

The library is mature enough to be used in public commercial and academic projects. The library was used in internal projects and refined to
fulfill these requirements. More customers will validate the usefulness of the library and identify extensions for further releases.

=== Decision

The library shall be published on maven central and be accessible to a wide range of developers and organizations. A website shall be set up to
provide an adequate documentation for users.

The https://tangly-team.bitbucket.io/fsm/[FSM website] will use a static web approach to minimize costs and provide good legibility.

The library will be published on Maven Central to maximize potential usage.

The ADR FSM-001 supports this evolution.

=== Consequences

* We have to establish a publishing process at the company level to deploy signed artifacts to maven central repository.
* We have to establish a public website to host the documentation of public published libraries
* We have to support semantic versioning for all future releases of public published libraries
